"""Seed Part 4: Shopping & Money (40 words)"""
SEED_PART4 = [
  {"estonian":"pood","finnish":"kauppa","et":"Pood on avatud.","fi":"Kauppa on auki.","cat":"shopping","cog":0,"d":1},
  {"estonian":"maksumärk","finnish":"hinta","et":"Kui palju see maksab?","fi":"Kuinka paljon tämä maksaa?","cat":"shopping","cog":0,"d":1},
  {"estonian":"soodne","finnish":"halpa","et":"See on väga soodne.","fi":"Tämä on erittäin halpa.","cat":"shopping","cog":0,"d":2},
  {"estonian":"kallis","finnish":"kallis","et":"See on liiga kallis.","fi":"Tämä on liian kallis.","cat":"shopping","cog":1,"d":1},
  {"estonian":"ostma","finnish":"ostaa","et":"Ma tahan osta seda.","fi":"Haluan ostaa tämän.","cat":"shopping","cog":0,"d":1},
  {"estonian":"müüma","finnish":"myydä","et":"Nad müüvad head toitu.","fi":"He myyvät hyvää ruokaa.","cat":"shopping","cog":0,"d":2},
  {"estonian":"kassa","finnish":"kassa","et":"Kassa on tühi.","fi":"Kassa on tyhjä.","cat":"shopping","cog":1,"d":1},
  {"estonian":"kviitung","finnish":"kuitti","et":"Kas saan kviitungi?","fi":"Saanko kuitin?","cat":"shopping","cog":0,"d":2},
  {"estonian":"allahindlus","finnish":"alennus","et":"Kas on allahindlust?","fi":"Onko alennusta?","cat":"shopping","cog":0,"d":2},
  {"estonian":"soodus","finnish":"tarjous","et":"Head soodustused!","fi":"Hyvät tarjoukset!","cat":"shopping","cog":0,"d":2},
  {"estonian":"euro","finnish":"euro","et":"See maksab viis eurot.","fi":"Tämä maksaa viisi euroa.","cat":"shopping","cog":1,"d":1},
  {"estonian":"sent","finnish":"sentti","et":"Viiskümmend senti.","fi":"Viisikymmentä senttiä.","cat":"shopping","cog":0,"d":1},
  {"estonian":"raha","finnish":"raha","et":"Kus on mu raha?","fi":"Missä on rahani?","cat":"shopping","cog":1,"d":1},
  {"estonian":"pangaautomaat","finnish":"pankkiautomaatti","et":"Pangaautomaat on siin.","fi":"Pankkiautomaatti on täällä.","cat":"shopping","cog":0,"d":3},
  {"estonian":"kaardimakse","finnish":"korttimaksu","et":"Kas saan kaardiga maksta?","fi":"Voinko maksaa kortilla?","cat":"shopping","cog":0,"d":2},
  {"estonian":"sularaha","finnish":"käteinen","et":"Ma maksan sularahas.","fi":"Maksan käteisellä.","cat":"shopping","cog":0,"d":2},
  {"estonian":"kilekott","finnish":"laukku","et":"Kus on mu kilekott?","fi":"Missä on laukkuni?","cat":"shopping","cog":0,"d":2},
  {"estonian":"müügikott","finnish":"ostoskassi","et":"Kas võtan müügikoti?","fi":"Ottanko ostoskassin?","cat":"shopping","cog":0,"d":2},
  {"estonian":"suurpood","finnish":"market","et":"Suurpood on lähedal.","fi":"Market on lähellä.","cat":"shopping","cog":0,"d":1},
  {"estonian":"turg","finnish":"tori","et":"Turg on avatud.","fi":"Tori on auki.","cat":"shopping","cog":0,"d":1},
  {"estonian":"müüja","finnish":"myyjä","et":"Kus on müüja?","fi":"Missä on myyjä?","cat":"shopping","cog":0,"d":2},
  {"estonian":"klienditeenindus","finnish":"asiakaspalvelu","et":"Klienditeenindus on seal.","fi":"Asiakaspalvelu on tuolla.","cat":"shopping","cog":0,"d":3},
  {"estonian":"tagastama","finnish":"palauttaa","et":"Ma tahan tagastada selle.","fi":"Haluan palauttaa tämän.","cat":"shopping","cog":0,"d":3},
  {"estonian":"vahetama","finnish":"vaihtaa","et":"Ma tahan vahetada suurust.","fi":"Haluan vaihtaa kokoa.","cat":"shopping","cog":0,"d":2},
  {"estonian":"suurus","finnish":"koko","et":"Kas on suuremat suurust?","fi":"Onko isompaa kokoa?","cat":"shopping","cog":0,"d":2},
  {"estonian":"proovida","finnish":"kokeilla","et":"Kas ma saan proovida?","fi":"Voinko kokeilla?","cat":"shopping","cog":0,"d":2},
  {"estonian":"peegel","finnish":"peili","et":"Kus on peegel?","fi":"Missä on peili?","cat":"shopping","cog":0,"d":1},
  {"estonian":"köide","finnish":"nauha","et":"Köide on katki.","fi":"Nauha on poikki.","cat":"shopping","cog":0,"d":3},
  {"estonian":"pakend","finnish":"pakkaus","et":"Pakend on kahjustatud.","fi":"Pakkaus on vahingoittunut.","cat":"shopping","cog":0,"d":3},
  {"estonian":"broneerima","finnish":"varata","et":"Ma tahan broneerida laua.","fi":"Haluan varata pöydän.","cat":"shopping","cog":0,"d":3},
  {"estonian":"tellima","finnish":"tilata","et":"Ma tellin uue raamatu.","fi":"Tilasin uuden kirjan.","cat":"shopping","cog":0,"d":2},
  {"estonian":"kohaletoimetamine","finnish":"toimitus","et":"Kohaletoimetamine on tasuta.","fi":"Toimitus on ilmainen.","cat":"shopping","cog":0,"d":3},
  {"estonian":"laos","finnish":"varastossa","et":"See on laos olemas.","fi":"Tämä on varastossa.","cat":"shopping","cog":0,"d":2},
  {"estonian":"väljas","finnish":"loppu","et":"See on müüdud.","fi":"Tämä on loppu.","cat":"shopping","cog":0,"d":2},
  {"estonian":"kampaania","finnish":"kampanja","et":"Kampaania kestab nädal aega.","fi":"Kampanja kestää viikon.","cat":"shopping","cog":0,"d":3},
  {"estonian":"kliendikaart","finnish":"kortti","et":"Kas sul on kliendikaart?","fi":"Onko sinulla korttia?","cat":"shopping","cog":0,"d":2},
  {"estonian":"püsiklient","finnish":"kanta-asiakas","et":"Ma olen püsiklient.","fi":"Olen kanta-asiakas.","cat":"shopping","cog":0,"d":3},
  {"estonian":"järjekord","finnish":"jono","et":"Järjekord on pikk.","fi":"Jono on pitkä.","cat":"shopping","cog":0,"d":2},
  {"estonian":"kohvituba","finnish":"kahvila","et":"Kohvituba on meeldiv.","fi":"Kahvila on miellyttävä.","cat":"shopping","cog":0,"d":2},
  {"estonian":"restoran","finnish":"ravintola","et":"Restoran on täis.","fi":"Ravintola on täynnä.","cat":"shopping","cog":0,"d":1},
  {"estonian":"jätma","finnish":"jättää","et":"Ma jätin raha laua peale.","fi":"Jätin rahan pöydälle.","cat":"shopping","cog":0,"d":2},
]
