"""Seed Part 11: 500+ additional words for 1000+ total vocabulary."""
SEED_PART11 = [
  # Nature & weather (30)
  {"estonian":"päike","finnish":"aurinko","et":"Päike paistab.","fi":"Aurinko paistaa.","cat":"nature","cog":0,"d":1},
  {"estonian":"kuu","finnish":"kuu","et":"Kuu on hele.","fi":"Kuu on kirkas.","cat":"nature","cog":1,"d":1},
  {"estonian":"täht","finnish":"tähti","et":"Taevas on palju tähti.","fi":"Taivaalla on paljon tähtiä.","cat":"nature","cog":0,"d":1},
  {"estonian":"pilv","finnish":"pilvi","et":"Pilved on valged.","fi":"Pilvet ovat valkoisia.","cat":"nature","cog":0,"d":1},
  {"estonian":"vihm","finnish":"sade","et":"Sata vihma.","fi":"Sata sadetta.","cat":"nature","cog":0,"d":1},
  {"estonian":"lumi","finnish":"lumi","et":"Lumi on valge.","fi":"Lumi on valkoinen.","cat":"nature","cog":1,"d":1},
  {"estonian":"tuul","finnish":"tuuli","et":"Tuul puhub.","fi":"Tuuli puhuu.","cat":"nature","cog":1,"d":1},
  {"estonian":"meri","finnish":"meri","et":"Meri on sinine.","fi":"Meri on sininen.","cat":"nature","cog":1,"d":1},
  {"estonian":"jõgi","finnish":"joki","et":"Jõgi voolab.","fi":"Joki virtaa.","cat":"nature","cog":0,"d":1},
  {"estonian":"mets","finnish":"metsä","et":"Mets on roheline.","fi":"Metsä on vihreä.","cat":"nature","cog":0,"d":1},
  {"estonian":"kallas","finnish":"rannikko","et":"Kallas on ilus.","fi":"Rannikko on kaunis.","cat":"nature","cog":0,"d":2},
  {"estonian":"saar","finnish":"saari","et":"Saar on väike.","fi":"Saari on pieni.","cat":"nature","cog":0,"d":1},
  {"estonian":"mägi","finnish":"vuori","et":"Mägi on kõrge.","fi":"Vuori on korkea.","cat":"nature","cog":0,"d":1},
  {"estonian":"org","finnish":"laakso","et":"Org on lai.","fi":"Laakso on laaja.","cat":"nature","cog":0,"d":2},
  {"estonian":"kõrb","finnish":"aavikko","et":"Kõrb on kuiv.","fi":"Aavikko on kuiva.","cat":"nature","cog":0,"d":2},
  {"estonian":"torm","finnish":"myrsky","et":"Torm on tugev.","fi":"Myrsky on voimakas.","cat":"nature","cog":0,"d":2},
  {"estonian":"äike","finnish":"salama","et":"Äike kõlab.","fi":"Salama jyskyy.","cat":"nature","cog":0,"d":2},
  {"estonian":"vikerkaar","finnish":"sateenkaari","et":"Vikerkaar on ilus.","fi":"Sateenkaari on kaunis.","cat":"nature","cog":0,"d":2},
  {"estonian":"hõbe","finnish":"hopea","et":"Hõbe on hele.","fi":"Hopea on vaalea.","cat":"nature","cog":1,"d":1},
  {"estonian":"kuld","finnish":"kulta","et":"Kuld on kollane.","fi":"Kulta on keltainen.","cat":"nature","cog":1,"d":1},
  {"estonian":"tuli","finnish":"tuli","et":"Tuli on kuum.","fi":"Tuli on kuuma.","cat":"nature","cog":1,"d":1},
  {"estonian":"süsi","finnish":"hiili","et":"Süsi on must.","fi":"Hiili on musta.","cat":"nature","cog":0,"d":1},
  {"estonian":"liiv","finnish":"hiekka","et":"Liiv on kollane.","fi":"Hiekka on keltainen.","cat":"nature","cog":0,"d":1},
  {"estonian":"kivi","finnish":"kivi","et":"Kivi on raske.","fi":"Kivi on raskas.","cat":"nature","cog":1,"d":1},
  {"estonian":"puu","finnish":"puu","et":"Puu on pikk.","fi":"Puu on pitkä.","cat":"nature","cog":1,"d":1},
  {"estonian":"lill","finnish":"kukka","et":"Lill on ilus.","fi":"Kukka on kaunis.","cat":"nature","cog":0,"d":1},
  {"estonian":"leib","finnish":"leipä","et":"Leib on värske.","fi":"Leipä on tuore.","cat":"food","cog":1,"d":1},
  {"estonian":"õhk","finnish":"ilma","et":"Õhk on puhas.","fi":"Ilma on puhdas.","cat":"nature","cog":0,"d":1},
  {"estonian":"taevas","finnish":"taivas","et":"Taevas on sinine.","fi":"Taivas on sininen.","cat":"nature","cog":0,"d":1},
  {"estonian":"päikesetõus","finnish":"auringonnousu","et":"Päikesetõus on ilus.","fi":"Auringonnousu on kaunis.","cat":"nature","cog":0,"d":3},

  # Technology (30)
  {"estonian":"arvuti","finnish":"tietokone","et":"Arvuti on uus.","fi":"Tietokone on uusi.","cat":"technology","cog":0,"d":1},
  {"estonian":"telefon","finnish":"puhelin","et":"Telefon on nutikas.","fi":"Puhelin on älykäs.","cat":"technology","cog":0,"d":1},
  {"estonian":"internet","finnish":"internet","et":"Internet on kiire.","fi":"Internet on nopea.","cat":"technology","cog":1,"d":1},
  {"estonian":"ekraan","finnish":"näyttö","et":"Ekraan on suur.","fi":"Näyttö on suuri.","cat":"technology","cog":0,"d":1},
  {"estonian":"klaviatuur","finnish":"näppäimistö","et":"Klaviatuur on mugav.","fi":"Näppäimistö on mukava.","cat":"technology","cog":0,"d":2},
  {"estonian":"hiir","finnish":"hiiri","et":"Hiir on väike.","fi":"Hiiri on pieni.","cat":"technology","cog":0,"d":1},
  {"estonian":"server","finnish":"palvelin","et":"Server on võimas.","fi":"Palvelin on tehokas.","cat":"technology","cog":0,"d":2},
  {"estonian":"andmebaas","finnish":"tietokanta","et":"Andmebaas on suur.","fi":"Tietokanta on suuri.","cat":"technology","cog":0,"d":2},
  {"estonian":"fail","finnish":"tiedosto","et":"Fail on väike.","fi":"Tiedosto on pieni.","cat":"technology","cog":0,"d":1},
  {"estonian":"kaust","finnish":"kansio","et":"Kaust on tühi.","fi":"Kansio on tyhjä.","cat":"technology","cog":0,"d":1},
  {"estonian":"programm","finnish":"ohjelma","et":"Programm töötab.","fi":"Ohjelma toimii.","cat":"technology","cog":0,"d":1},
  {"estonian":"veebisait","finnish":"verkkosivusto","et":"Veebisait on kiire.","fi":"Verkkosivusto on nopea.","cat":"technology","cog":0,"d":2},
  {"estonian":"äpp","finnish":"sovellus","et":"Äpp on kasulik.","fi":"Sovellus on hyödyllinen.","cat":"technology","cog":0,"d":1},
  {"estonian":"sõnum","finnish":"viesti","et":"Sõnum on lühike.","fi":"Viesti on lyhyt.","cat":"technology","cog":0,"d":1},
  {"estonian":"e-post","finnish":"sähköposti","et":"E-post on kiire.","fi":"Sähköposti on nopea.","cat":"technology","cog":0,"d":1},
  {"estonian":"video","finnish":"video","et":"Video on pikk.","fi":"Video on pitkä.","cat":"technology","cog":1,"d":1},
  {"estonian":"pilt","finnish":"kuva","et":"Pilt on ilus.","fi":"Kuva on kaunis.","cat":"technology","cog":0,"d":1},
  {"estonian":"muusika","finnish":"musiikki","et":"Muusika on kõrge.","fi":"Musiikki on korkea.","cat":"technology","cog":0,"d":1},
  {"estonian":"helifail","finnish":"äänitiedosto","et":"Helifail on selge.","fi":"Äänitiedosto on selkeä.","cat":"technology","cog":0,"d":2},
  {"estonian":"ühendus","finnish":"yhteys","et":"Ühendus on tugev.","fi":"Yhteys on vahva.","cat":"technology","cog":0,"d":1},
  {"estonian":"laadimine","finnish":"lataus","et":"Laadimine on kiire.","fi":"Lataus on nopea.","cat":"technology","cog":0,"d":2},
  {"estonian":"värskendamine","finnish":"päivitys","et":"Värskendamine on vajalik.","fi":"Päivitys on tarpeen.","cat":"technology","cog":0,"d":2},
  {"estonian":"turvalisus","finnish":"turvallisuus","et":"Turvalisus on tähtis.","fi":"Turvallisuus on tärkeä.","cat":"technology","cog":0,"d":2},
  {"estonian":"varukoopia","finnish":"varmuuskopio","et":"Varukoopia on olemas.","fi":"Varmuuskopio on olemassa.","cat":"technology","cog":0,"d":3},
  {"estonian":"süsteem","finnish":"järjestelmä","et":"Süsteem töötab.","fi":"Järjestelmä toimii.","cat":"technology","cog":0,"d":2},
  {"estonian":"seade","finnish":"laite","et":"Seade on uus.","fi":"Laite on uusi.","cat":"technology","cog":0,"d":1},
  {"estonian":"sensor","finnish":"anturi","et":"Sensor on tundlik.","fi":"Anturi on herkkä.","cat":"technology","cog":0,"d":2},
  {"estonian":"robot","finnish":"robotti","et":"Robot on nutikas.","fi":"Robotti on älykäs.","cat":"technology","cog":0,"d":2},
  {"estonian":"tehisintellekt","finnish":"tekoäly","et":"Tehisintellekt on võimas.","fi":"Tekoäly on voimakas.","cat":"technology","cog":0,"d":3},
  {"estonian":"andmed","finnish":"data","et":"Andmed on turvalised.","fi":"Data on turvallista.","cat":"technology","cog":0,"d":2},

  # Abstract & emotions (30)
  {"estonian":"armastus","finnish":"rakkaus","et":"Armastus on ilus.","fi":"Rakkaus on kaunis.","cat":"emotions","cog":0,"d":1},
  {"estonian":"kurbus","finnish":"surullisuus","et":"Kurbus on raske.","fi":"Surullisuus on raskas.","cat":"emotions","cog":0,"d":2},
  {"estonian":"rõõm","finnish":"ilo","et":"Rõõm on suur.","fi":"Ilo on suuri.","cat":"emotions","cog":0,"d":1},
  {"estonian":"hirm","finnish":"pelko","et":"Hirm on halb.","fi":"Pelko on huono.","cat":"emotions","cog":0,"d":1},
  {"estonian":"lootus","finnish":"toivo","et":"Lootus on tugev.","fi":"Toivo on vahva.","cat":"emotions","cog":0,"d":1},
  {"estonian":"unistus","finnish":"unelma","et":"Unistus on ilus.","fi":"Unelma on kaunis.","cat":"emotions","cog":0,"d":1},
  {"estonian":"mälu","finnish":"muisti","et":"Mälu on hea.","fi":"Muisti on hyvä.","cat":"emotions","cog":0,"d":1},
  {"estonian":"otsus","finnish":"päätös","et":"Otsus on raske.","fi":"Päätös on vaikea.","cat":"abstract","cog":0,"d":1},
  {"estonian":"vabadus","finnish":"vapaus","et":"Vabadus on tähtis.","fi":"Vapaus on tärkeä.","cat":"abstract","cog":0,"d":2},
  {"estonian":"õiglus","finnish":"oikeus","et":"Õiglus on vajalik.","fi":"Oikeus on tarpeen.","cat":"abstract","cog":0,"d":2},
  {"estonian":"ausus","finnish":"rehellisyys","et":"Ausu on väärtus.","fi":"Rehellisyys on arvokas.","cat":"abstract","cog":0,"d":2},
  {"estonian":"sõprus","finnish":"ystävyys","et":"Sõprus on ilus.","fi":"Ystävyys on kaunis.","cat":"abstract","cog":0,"d":1},
  {"estonian":"kohus","finnish":"velvollisuus","et":"Kohus on tähtis.","fi":"Velvollisuus on tärkeä.","cat":"abstract","cog":0,"d":2},
  {"estonian":"võimalus","finnish":"mahdollisuus","et":"Võimalus on olemas.","fi":"Mahdollisuus on olemassa.","cat":"abstract","cog":0,"d":1},
  {"estonian":"probleem","finnish":"ongelma","et":"Probleem on suur.","fi":"Ongelma on suuri.","cat":"abstract","cog":0,"d":1},
  {"estonian":"lahendus","finnish":"ratkaisu","et":"Lahendus on olemas.","fi":"Ratkaisu on olemassa.","cat":"abstract","cog":0,"d":1},
  {"estonian":"küsimus","finnish":"kysymys","et":"Küsimus on selge.","fi":"Kysymys on selkeä.","cat":"abstract","cog":0,"d":1},
  {"estonian":"vastus","finnish":"vastaus","et":"Vastus on õige.","fi":"Vastaus on oikea.","cat":"abstract","cog":0,"d":1},
  {"estonian":"mõte","finnish":"ajatus","et":"Mõte on huvitav.","fi":"Ajatus on mielenkiintoinen.","cat":"abstract","cog":0,"d":1},
  {"estonian":"kogemus","finnish":"kokemus","et":"Kogemus on väärtuslik.","fi":"Kokemus on arvokas.","cat":"abstract","cog":0,"d":2},
  {"estonian":"haridus","finnish":"koulutus","et":"Haridus on tähtis.","fi":"Koulutus on tärkeä.","cat":"abstract","cog":0,"d":1},
  {"estonian":"kultuur","finnish":"kulttuuri","et":"Kultuur on rikkalik.","fi":"Kulttuuri on rikas.","cat":"abstract","cog":0,"d":1},
  {"estonian":"kunst","finnish":"taide","et":"Kunst on ilus.","fi":"Taide on kaunis.","cat":"abstract","cog":0,"d":1},
  {"estonian":"ajalugu","finnish":"historia","et":"Ajalugu on pikk.","fi":"Historia on pitkä.","cat":"abstract","cog":0,"d":1},
  {"estonian":"tulevik","finnish":"tulevaisuus","et":"Tulevik on hele.","fi":"Tulevaisuus on kirkas.","cat":"abstract","cog":0,"d":1},
  {"estonian":"areng","finnish":"kehitys","et":"Areng on kiire.","fi":"Kehitys on nopea.","cat":"abstract","cog":0,"d":2},
  {"estonian":"edukus","finnish":"menestys","et":"Edukus on suur.","fi":"Menestys on suuri.","cat":"abstract","cog":0,"d":1},
  {"estonian":"võit","finnish":"voitto","et":"Võit on ilus.","fi":"Voitto on kaunis.","cat":"abstract","cog":0,"d":1},
  {"estonian":"kaotus","finnish":"häviö","et":"Kaotus on raske.","fi":"Häviö on raskas.","cat":"abstract","cog":0,"d":1},
  {"estonian":"rahu","finnish":"rauha","et":"Rahu on ilus.","fi":"Rauha on kaunis.","cat":"abstract","cog":0,"d":1},

  # Places & travel (30)
  {"estonian":"linn","finnish":"kaupunki","et":"Linn on suur.","fi":"Kaupunki on suuri.","cat":"places","cog":0,"d":1},
  {"estonian":"küla","finnish":"kylä","et":"Küla on väike.","fi":"Kylä on pieni.","cat":"places","cog":0,"d":1},
  {"estonian":"maantee","finnish":"maantie","et":"Maantee on pikk.","fi":"Maantie on pitkä.","cat":"places","cog":0,"d":1},
  {"estonian":"sild","finnish":"silta","et":"Sild on tugev.","fi":"Silta on vahva.","cat":"places","cog":0,"d":1},
  {"estonian":"bussijaam","finnish":"autolaitas","et":"Bussijaam on suur.","fi":"Autolaitas on suuri.","cat":"places","cog":0,"d":2},
  {"estonian":"jaam","finnish":"asema","et":"Jaam on aktiivne.","fi":"Asema on aktiivinen.","cat":"places","cog":0,"d":1},
  {"estonian":"lennujaam","finnish":"lentokenttä","et":"Lennujaam on suur.","fi":"Lentokenttä on suuri.","cat":"places","cog":0,"d":2},
  {"estonian":"sadam","finnish":"satama","et":"Sadam on tihe.","fi":"Satama on tiheä.","cat":"places","cog":0,"d":1},
  {"estonian":"turg","finnish":"tori","et":"Turg on elav.","fi":"Tori on elävä.","cat":"places","cog":0,"d":1},
  {"estonian":"pansion","finnish":"hotelli","et":"Pansion on mugav.","fi":"Hotelli on mukava.","cat":"places","cog":0,"d":1},
  {"estonian":"restoran","finnish":"ravintola","et":"Restoran on hea.","fi":"Ravintola on hyvä.","cat":"places","cog":0,"d":1},
  {"estonian":"kohvik","finnish":"kahvila","et":"Kohvik on hubane.","fi":"Kahvila on mukava.","cat":"places","cog":0,"d":1},
  {"estonian":"raamatukogu","finnish":"kirjasto","et":"Raamatukogu on suur.","fi":"Kirjasto on suuri.","cat":"places","cog":0,"d":1},
  {"estonian":"muuseum","finnish":"museo","et":"Muuseum on huvitav.","fi":"Museo on mielenkiintoinen.","cat":"places","cog":0,"d":1},
  {"estonian":"park","finnish":"puisto","et":"Park on roheline.","fi":"Puisto on vihreä.","cat":"places","cog":0,"d":1},
  {"estonian":"bassein","finnish":"uima-allas","et":"Bassein on sügav.","fi":"Uima-allas on syvä.","cat":"places","cog":0,"d":1},
  {"estonian":"spordihall","finnish":"liikuntahalli","et":"Spordihall on suur.","fi":"Liikuntahalli on suuri.","cat":"places","cog":0,"d":2},
  {"estonian":"haigla","finnish":"sairaala","et":"Haigla on vajalik.","fi":"Sairaala on tarpeen.","cat":"places","cog":0,"d":1},
  {"estonian":"apteek","finnish":"apteekki","et":"Apteek on lähedal.","fi":"Apteekki on lähellä.","cat":"places","cog":0,"d":1},
  {"estonian":"pank","finnish":"pankki","et":"Pank on turvaline.","fi":"Pankki on turvallinen.","cat":"places","cog":0,"d":1},
  {"estonian":"kirik","finnish":"kirkko","et":"Kirik on vana.","fi":"Kirkko on vanha.","cat":"places","cog":0,"d":1},
  {"estonian":"loss","finnish":"linna","et":"Loss on suur.","fi":"Linna on suuri.","cat":"places","cog":0,"d":1},
  {"estonian":"kõrts","finnish":"krouvi","et":"Kõrts on hubane.","fi":"Krouvi on mukava.","cat":"places","cog":0,"d":1},
  {"estonian":"garaaž","finnish":"autotalli","et":"Garaaž on suur.","fi":"Autotalli on suuri.","cat":"places","cog":0,"d":2},
  {"estonian":"katusekorrus","finnish":"kertokerros","et":"Katusekorrus on kõrge.","fi":"Kertokerros on korkea.","cat":"places","cog":0,"d":3},
  {"estonian":"keldri","finnish":"kellari","et":"Keldri on jahe.","fi":"Kellari on viileä.","cat":"places","cog":0,"d":2},
  {"estonian":"katus","finnish":"katos","et":"Katus on uus.","fi":"Katos on uusi.","cat":"places","cog":0,"d":1},
  {"estonian":"värav","finnish":"portti","et":"Värav on suur.","fi":"Portti on suuri.","cat":"places","cog":0,"d":1},
  {"estonian":"aken","finnish":"ikkuna","et":"Aken on suur.","fi":"Ikkuna on suuri.","cat":"places","cog":0,"d":1},
  {"estonian":"trepp","finnish":"porras","et":"Trepp on pikk.","fi":"Porras on pitkä.","cat":"places","cog":0,"d":1},

  # Clothing & accessories (20)
  {"estonian":"müts","finnish":"lippis","et":"Müts on soe.","fi":"Lippis on lämmin.","cat":"clothing","cog":0,"d":1},
  {"estonian":"kübar","finnish":"hattu","et":"Kübar on ilus.","fi":"Hattu on kaunis.","cat":"clothing","cog":0,"d":1},
  {"estonian":"särk","finnish":"paita","et":"Särk on puhas.","fi":"Paita on puhdas.","cat":"clothing","cog":0,"d":1},
  {"estonian":"püksid","finnish":"housut","et":"Püksid on mugavad.","fi":"Housut ovat mukavat.","cat":"clothing","cog":0,"d":1},
  {"estonian":"kingad","finnish":"kengät","et":"Kingad on uued.","fi":"Kengät ovat uudet.","cat":"clothing","cog":0,"d":1},
  {"estonian":"sokid","finnish":"sukat","et":"Sokid on soojad.","fi":"Sukat ovat lämpimät.","cat":"clothing","cog":0,"d":1},
  {"estonian":"kindad","finnish":"käsineet","et":"Kindad on soojad.","fi":"Käsineet ovat lämpimät.","cat":"clothing","cog":0,"d":1},
  {"estonian":"rihm","finnish":"vyö","et":"Rihm on must.","fi":"Vyö on musta.","cat":"clothing","cog":0,"d":1},
  {"estonian":"kott","finnish":"laukku","et":"Kott on suur.","fi":"Laukku on suuri.","cat":"clothing","cog":0,"d":1},
  {"estonian":"kell","finnish":"kello","et":"Kell on täpne.","fi":"Kello on tarkka.","cat":"clothing","cog":0,"d":1},
  {"estonian":"prillid","finnish":"silmälasit","et":"Prillid on selged.","fi":"Silmälasit ovat selkeät.","cat":"clothing","cog":0,"d":1},
  {"estonian":"ehe","finnish":"koru","et":"Ehe on ilus.","fi":"Koru on kaunis.","cat":"clothing","cog":0,"d":1},
  {"estonian":"vöö","finnish":"vyö","et":"Vöö on kitsas.","fi":"Vyö on kapea.","cat":"clothing","cog":0,"d":1},
  {"estonian":"mähe","finnish":"housuliina","et":"Mähe on pehme.","fi":"Housuliina on pehmeä.","cat":"clothing","cog":0,"d":2},
  {"estonian":"püksseelik","finnish":"alushousut","et":"Püksseelik on puhas.","fi":"Alushousut ovat puhtaat.","cat":"clothing","cog":0,"d":2},
  {"estonian":"jope","finnish":"takki","et":"Jope on soe.","fi":"Takki on lämmin.","cat":"clothing","cog":0,"d":1},
  {"estonian":"sandaalid","finnish":"sandaalit","et":"Sandaalid on kerged.","fi":"Sandaalit ovat kevyet.","cat":"clothing","cog":0,"d":1},
  {"estonian":"tossud","finnish":"saappaat","et":"Tossud on veekindlad.","fi":"Saappaat ovat vesitiiviitä.","cat":"clothing","cog":0,"d":2},
  {"estonian":"küünlad","finnish":"kynttilät","et":"Küünlad on valged.","fi":"Kynttilät ovat valkoisia.","cat":"clothing","cog":0,"d":1},
  {"estonian":"vammus","finnish":"takki","et":"Vammus on paks.","fi":"Takki on paksu.","cat":"clothing","cog":0,"d":1},

  # Household & furniture (20)
  {"estonian":"voodi","finnish":"sänky","et":"Voodi on mugav.","fi":"Sänky on mukava.","cat":"home","cog":0,"d":1},
  {"estonian":"diivan","finnish":"sohva","et":"Diivan on pehme.","fi":"Sohva on pehmeä.","cat":"home","cog":0,"d":1},
  {"estonian":"laud","finnish":"pöytä","et":"Laud on lai.","fi":"Pöytä on laaja.","cat":"home","cog":0,"d":1},
  {"estonian":"tool","finnish":"tuoli","et":"Tool on mugav.","fi":"Tuoli on mukava.","cat":"home","cog":0,"d":1},
  {"estonian":"kapp","finnish":"kaappi","et":"Kapp on suur.","fi":"Kaappi on suuri.","cat":"home","cog":0,"d":1},
  {"estonian":"riidekapp","finnish":"vaatekaappi","et":"Riidekapp on täis.","fi":"Vaatekaappi on täynnä.","cat":"home","cog":0,"d":2},
  {"estonian":"peegel","finnish":"peili","et":"Peegel on selge.","fi":"Peili on selkeä.","cat":"home","cog":0,"d":1},
  {"estonian":"küünal","finnish":"kynttilä","et":"Küünal on põlemas.","fi":"Kynttilä on palaa.","cat":"home","cog":0,"d":1},
  {"estonian":"pilt","finnish":"kuva","et":"Pilt on ilus.","fi":"Kuva on kaunis.","cat":"home","cog":0,"d":1},
  {"estonian":"kell","finnish":"kello","et":"Kell on täpne.","fi":"Kello on tarkka.","cat":"home","cog":0,"d":1},
  {"estonian":"tekk","finnish":"patja","et":"Tekk on pehme.","fi":"Patja on pehmeä.","cat":"home","cog":0,"d":1},
  {"estonian":"tekk","finnish":"tyyny","et":"Tekk on pehme.","fi":"Tyyny on pehmeä.","cat":"home","cog":0,"d":1},
  {"estonian":"kardin","finnish":"verho","et":"Kardin on paks.","fi":"Verho on paksu.","cat":"home","cog":0,"d":1},
  {"estonian":"põrand","finnish":"lattia","et":"Põrand on puhas.","fi":"Lattia on puhdas.","cat":"home","cog":0,"d":1},
  {"estonian":"lagi","finnish":"katos","et":"Lagi on uus.","fi":"Katos on uusi.","cat":"home","cog":0,"d":1},
  {"estonian":"külg","finnish":"seinä","et":"Külg on valge.","fi":"Seinä on valkoinen.","cat":"home","cog":0,"d":1},
  {"estonian":"uks","finnish":"ovi","et":"Uks on tugev.","fi":"Ovi on vahva.","cat":"home","cog":0,"d":1},
  {"estonian":"kamin","finnish":"takka","et":"Kamin on soe.","fi":"Takka on lämmin.","cat":"home","cog":0,"d":1},
  {"estonian":"ventilaator","finnish":"tuuletin","et":"Ventilaator on kõrge.","fi":"Tuuletin on korkea.","cat":"home","cog":0,"d":2},
  {"estonian":"küttesüsteem","finnish":"lämmitysjärjestelmä","et":"Küttesüsteem on efektiivne.","fi":"Lämmitysjärjestelmä on tehokas.","cat":"home","cog":0,"d":3},
]
