"""Seed Part 12: 1000 most important Estonian-Finnish words & phrases.
Based on frequency analysis, CEFR A1-B2 vocabulary, and EKI core vocabulary.
Categories: basic, daily life, work, society, abstract, connectors, multi-word expressions.
"""
SEED_PART12 = [
  # === PRONOUNS & DETERMINERS (20) ===
  {"estonian":"mina","finnish":"minä","et":"Mina olen õpilane.","fi":"Minä olen opiskelija.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"sina","finnish":"sinä","et":"Sina oled sõber.","fi":"Sinä olet ystävä.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"tema","finnish":"hän","et":"Tema on õpetaja.","fi":"Hän on opettaja.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"meie","finnish":"me","et":"Meie oleme õpilased.","fi":"Me olemme opiskelijat.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"teie","finnish":"te","et":"Teie olete õpetajad.","fi":"Te olette opettajat.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"nemad","finnish":"he","et":"Nemad on sõbrad.","fi":"He ovat ystäviä.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"see","finnish":"tämä","et":"See on mu raamat.","fi":"Tämä on kirjani.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"too","finnish":"tuo","et":"Too on suur.","fi":"Tuo on suuri.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"seal","finnish":"tuolla","et":"Seal on pood.","fi":"Tuolla on kauppa.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"siin","finnish":"täällä","et":"Siin on külm.","fi":"Täällä on kylmä.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"kes","finnish":"kuka","et":"Kes sa oled?","fi":"Kuka sinä olet?","cat":"pronouns","cog":0,"d":1},
  {"estonian":"mida","finnish":"mitä","et":"Mida sa teed?","fi":"Mitä sinä teet?","cat":"pronouns","cog":0,"d":1},
  {"estonian":"milline","finnish":"millaista","et":"Milline ilm on?","fi":"Millaista sää on?","cat":"pronouns","cog":0,"d":1},
  {"estonian":"kumb","finnish":"kumpi","et":"Kumb on parem?","fi":"Kumpi on parempi?","cat":"pronouns","cog":0,"d":1},
  {"estonian":"ise","finnish":"itse","et":"Ma ise teen.","fi":"Minä itse teen.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"keegi","finnish":"kukaan","et":"Keegi ei tea.","fi":"Kukaan ei tiedä.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"midagi","finnish":"mitään","et":"Ma ei tea midagi.","fi":"En tiedä mitään.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"mõlemad","finnish":"molemmat","et":"Mõlemad on terved.","fi":"Molemmat ovat terveitä.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"igaüks","finnish":"jokainen","et":"Igaüks on unikaalne.","fi":"Jokainen on ainutlaatuinen.","cat":"pronouns","cog":0,"d":2},
  {"estonian":"mitu","finnish":"usea","et":"Mitu korda?","fi":"Useita kertoja.","cat":"pronouns","cog":0,"d":1},

  # === VERBS - MOST COMMON (50) ===
  {"estonian":"olema","finnish":"olla","et":"Ma olen siin.","fi":"Minä olen täällä.","cat":"verbs","cog":1,"d":1},
  {"estonian":"tegema","finnish":"tehdä","et":"Ma teen tööd.","fi":"Minä teen työtä.","cat":"verbs","cog":0,"d":1},
  {"estonian":"minema","finnish":"mennä","et":"Ma lähen koju.","fi":"Menen kotiin.","cat":"verbs","cog":0,"d":1},
  {"estonian":"tulema","finnish":"tulla","et":"Tule siia!","fi":"Tule tänne!","cat":"verbs","cog":0,"d":1},
  {"estonian":"nägema","finnish":"nähdä","et":"Ma näen sind.","fi":"Näen sinut.","cat":"verbs","cog":0,"d":1},
  {"estonian":"kuulma","finnish":"kuulla","et":"Ma kuulen sind.","fi":"Kuulen sinut.","cat":"verbs","cog":0,"d":1},
  {"estonian":"ütlema","finnish":"sanoa","et":"Ma ütlen tere.","fi":"Sanon hei.","cat":"verbs","cog":0,"d":1},
  {"estonian":"küsima","finnish":"kysyä","et":"Ma küsin teed.","fi":"Kysyn tietä.","cat":"verbs","cog":0,"d":1},
  {"estonian":"vastama","finnish":"vastata","et":"Ma vastan küsimusele.","fi":"Vastaan kysymykseen.","cat":"verbs","cog":0,"d":2},
  {"estonian":"tundma","finnish":"tuntea","et":"Ma tunnen end hästi.","fi":"Tunnen itseni hyväksi.","cat":"verbs","cog":0,"d":2},
  {"estonian":"mõtlema","finnish":"ajatella","et":"Ma mõtlen sinust.","fi":"Ajattelen sinua.","cat":"verbs","cog":0,"d":1},
  {"estonian":"teadma","finnish":"tietää","et":"Ma tean vastust.","fi":"Tiedän vastauksen.","cat":"verbs","cog":0,"d":1},
  {"estonian":"paluma","finnish":"pyytää","et":"Ma palun sind.","fi":"Pyydän sinua.","cat":"verbs","cog":0,"d":1},
  {"estonian":"andma","finnish":"antaa","et":"Ma annan sulle.","fi":"Annan sinulle.","cat":"verbs","cog":0,"d":1},
  {"estonian":"võtma","finnish":"ottaa","et":"Ma võtan raamatu.","fi":"Otan kirjan.","cat":"verbs","cog":0,"d":1},
  {"estonian":"panema","finnish":"laittaa","et":"Ma panen lauale.","fi":"Laitan pöydälle.","cat":"verbs","cog":0,"d":1},
  {"estonian":"tõstma","finnish":"nostaa","et":"Ma tõstan kätt.","fi":"Nostan kättä.","cat":"verbs","cog":0,"d":1},
  {"estonian":"jätma","finnish":"jättää","et":"Ma jätan märgi.","fi":"Jätän merkin.","cat":"verbs","cog":0,"d":1},
  {"estonian":"tooma","finnish":"tuoda","et":"Ma toon toitu.","fi":"Tuon ruokaa.","cat":"verbs","cog":0,"d":1},
  {"estonian":"maksma","finnish":"maksaa","et":"Ma maksan arve.","fi":"Maksan laskun.","cat":"verbs","cog":0,"d":1},
  {"estonian":"ostma","finnish":"ostaa","et":"Ma ostin uue auto.","fi":"Ostin uuden auton.","cat":"verbs","cog":0,"d":1},
  {"estonian":"müüma","finnish":"myydä","et":"Nad müüvad head toitu.","fi":"He myyvät hyvää ruokaa.","cat":"verbs","cog":0,"d":1},
  {"estonian":"ühendama","finnish":"yhdistää","et":"Ma ühendan arvutiga.","fi":"Yhdistän tietokoneeseen.","cat":"verbs","cog":0,"d":2},
  {"estonian":"ootama","finnish":"odottaa","et":"Ma ootan bussi.","fi":"Odotan bussia.","cat":"verbs","cog":0,"d":1},
  {"estonian":"ootma","finnish":"pelätä","et":"Ma ootan hirmu.","fi":"Pelän pelkoa.","cat":"verbs","cog":0,"d":1},
  {"estonian":"elama","finnish":"asua","et":"Ma elan Tallinnas.","fi":"Asun Tallinnassa.","cat":"verbs","cog":0,"d":1},
  {"estonian":"töötama","finnish":"työskennellä","et":"Ma töötän kontoris.","fi":"Työskentelen toimistossa.","cat":"verbs","cog":0,"d":2},
  {"estonian":"õppima","finnish":"oppia","et":"Ma õpin soome keelt.","fi":"Opin suomea.","cat":"verbs","cog":0,"d":1},
  {"estonian":"õpetama","finnish":"opettaa","et":"Õpetaja õpetab matemaatikat.","fi":"Opettaja opettaa matematiikkaa.","cat":"verbs","cog":0,"d":2},
  {"estonian":"mängima","finnish":"pelata","et":"Lapsed mängivad.","fi":"Lapset leikkivät.","cat":"verbs","cog":0,"d":1},
  {"estonian":"jooksma","finnish":"juosta","et":"Ma jooksin pargis.","fi":"Juoksin puistossa.","cat":"verbs","cog":0,"d":1},
  {"estonian":"käima","finnish":"kävellä","et":"Ma käin tööl.","fi":"Kävelen töölle.","cat":"verbs","cog":0,"d":1},
  {"estonian":"sõitma","finnish":"ajaa","et":"Ma sõidan autoga.","fi":"Ajan autolla.","cat":"verbs","cog":0,"d":1},
  {"estonian":"magama","finnish":"nukkua","et":"Ma magan hästi.","fi":"Nukun hyvin.","cat":"verbs","cog":0,"d":1},
  {"estonian":"ärkama","finnish":"herätä","et":"Ma ärkan hommikul.","fi":"Herään aamulla.","cat":"verbs","cog":0,"d":1},
  {"estonian":"sööma","finnish":"syödä","et":"Ma söön õuna.","fi":"Syön omenaa.","cat":"verbs","cog":0,"d":1},
  {"estonian":"jooma","finnish":"juoda","et":"Ma joon vett.","fi":"Juon vettä.","cat":"verbs","cog":0,"d":1},
  {"estonian":"lugema","finnish":"lukea","et":"Ma loen raamatut.","fi":"Luen kirjaa.","cat":"verbs","cog":0,"d":1},
  {"estonian":"kirjutama","finnish":"kirjoittaa","et":"Ma kirjutan kirja.","fi":"Kirjoitan kirjeen.","cat":"verbs","cog":0,"d":2},
  {"estonian":"kuulma","finnish":"kuulla","et":"Ma kuulen muusikat.","fi":"Kuulen musiikkia.","cat":"verbs","cog":0,"d":1},
  {"estonian":"puhuma","finnish":"puhua","et":"Ma puhun eesti keelt.","fi":"Puhun suomea.","cat":"verbs","cog":0,"d":1},
  {"estonian":"rääkima","finnish":"puhua","et":"Ma räägin sinuga.","fi":"Puhun kanssasi.","cat":"verbs","cog":0,"d":1},
  {"estonian":"vaatama","finnish":"katsoa","et":"Ma vaatan televiisorit.","fi":"Katson telkkaria.","cat":"verbs","cog":0,"d":1},
  {"estonian":"otsima","finnish":"etsiä","et":"Ma otsin võtmeid.","fi":"Etsin avaimia.","cat":"verbs","cog":0,"d":1},
  {"estonian":"leidma","finnish":"löytää","et":"Ma leidsin võtme.","fi":"Löysin avaimen.","cat":"verbs","cog":0,"d":1},
  {"estonian":"saama","finnish":"saada","et":"Ma saan palju.","fi":"Saan paljon.","cat":"verbs","cog":0,"d":1},
  {"estonian":"võitma","finnish":"voittaa","et":"Ma võidan mängu.","fi":"Voitan pelin.","cat":"verbs","cog":0,"d":1},
  {"estonian":"kaotama","finnish":"hävittää","et":"Ma kaotasin võtme.","fi":"Hävitin avaimen.","cat":"verbs","cog":0,"d":1},
  {"estonian":"langema","finnish":"langata","et":"Mees langes.","fi":"Mies langettiin.","cat":"verbs","cog":0,"d":1},
  {"estonian":"tõusma","finnish":"nousta","et":"Päike tõuseb.","fi":"Aurinko nousee.","cat":"verbs","cog":0,"d":1},
  {"estonian":"kukkuma","finnish":"kuolla","et":"Aed kukub.","fi":"Puutarha kuolee.","cat":"verbs","cog":0,"d":1},
  {"estonian":"valmis","finnish":"valmis","et":"Olen valmis.","fi":"Olen valmis.","cat":"verbs","cog":1,"d":1},

  # === ADJECTIVES - MOST COMMON (40) ===
  {"estonian":"hea","finnish":"hyvä","et":"Toit on hea.","fi":"Ruoka on hyvä.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"halb","finnish":"huono","et":"Ilm on halb.","fi":"Sää on huono.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"suur","finnish":"suuri","et":"Maja on suur.","fi":"Talo on suuri.","cat":"adjectives","cog":1,"d":1},
  {"estonian":"väike","finnish":"pieni","et":"Laps on väike.","fi":"Lapsi on pieni.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"pikk","finnish":"pitkä","et":"Tee on pikk.","fi":"Tie on pitkä.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"lühike","finnish":"lyhyt","et":"Lugu on lühike.","fi":"Tarina on lyhyt.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"uus","finnish":"uusi","et":"Auto on uus.","fi":"Auto on uusi.","cat":"adjectives","cog":1,"d":1},
  {"estonian":"vana","finnish":"vanha","et":"Maja on vana.","fi":"Talo on vanha.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"ilus","finnish":"kaunis","et":"Ilm on ilus.","fi":"Sää on kaunis.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"kole","finnish":"ruma","et":"See on kole.","fi":"Tämä on ruma.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"kiire","finnish":"nopea","et":"Rong on kiire.","fi":"Juna on nopea.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"aeglane","finnish":"hidas","et":"Reis on aeglane.","fi":"Matka on hidas.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"raske","finnish":"raskas","et":"Kott on raske.","fi":"Laukku on raskas.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"kerge","finnish":"kevyt","et":"Lumi on kerge.","fi":"Lumi on kevyt.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"tugev","finnish":"vahva","et":"Tuul on tugev.","fi":"Tuuli on vahva.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"nõrk","finnish":"heikko","et":"Signaal on nõrk.","fi":"Signaali on heikko.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"õnnelik","finnish":"onnellinen","et":"Ma olen õnnelik.","fi":"Olen onnellinen.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"kurb","finnish":"surullinen","et":"Ta on kurb.","fi":"Hän on surullinen.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"vihane","finnish":"vihainen","et":"Ma olen vihane.","fi":"Olen vihainen.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"uhke","finnish":"ylpeä","et":"Ta on uhke.","fi":"Hän on ylpeä.","cat":"adjectives","cog":0,"d":2},
  {"estonian":"hirmunud","finnish":"pelokas","et":"Ta on hirmunud.","fi":"Hän on pelokas.","cat":"adjectives","cog":0,"d":2},
  {"estonian":"väsinud","finnish":"väsynyt","et":"Ma olen väsinud.","fi":"Olen väsynyt.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"näljane","finnish":"nälkäinen","et":"Ma olen näljane.","fi":"Olen nälkäinen.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"janune","finnish":"janoinen","et":"Ma olen janune.","fi":"Olen janoinen.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"külm","finnish":"kylmä","et":"Vesi on külm.","fi":"Vesi on kylmä.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"soe","finnish":"lämmin","et":"Küte on soe.","fi":"Lämmitys on lämmin.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"kuuma","finnish":"kuuma","et":"Kohv on kuuma.","fi":"Kahvi on kuuma.","cat":"adjectives","cog":1,"d":1},
  {"estonian":"mürgine","finnish":"myrkyllinen","et":"See on mürgine.","fi":"Tämä on myrkyllinen.","cat":"adjectives","cog":0,"d":3},
  {"estonian":"valge","finnish":"valkoinen","et":"Lumi on valge.","fi":"Lumi on valkoinen.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"must","finnish":"musta","et":"Öö on must.","fi":"Yö on musta.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"punane","finnish":"punainen","et":"Õis on punane.","fi":"Kukka on punainen.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"roheline","finnish":"vihreä","et":"Mets on roheline.","fi":"Metsä on vihreä.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"sinine","finnish":"sininen","et":"Meri on sinine.","fi":"Meri on sininen.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"kollane","finnish":"keltainen","et":"Päike on kollane.","fi":"Aurinko on keltainen.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"hall","finnish":"harmaa","et":"Pilv on hall.","fi":"Pilvi on harmaa.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"roosa","finnish":"vaaleanpunainen","et":"Taivas on roosa.","fi":"Taivas on vaaleanpunainen.","cat":"adjectives","cog":0,"d":2},
  {"estonian":"lilla","finnish":"violetti","et":"Lill on lilla.","fi":"Kukka on violetti.","cat":"adjectives","cog":0,"d":2},
  {"estonian":"tume","finnish":"tumma","et":"Öö on tume.","fi":"Yö on tumma.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"hele","finnish":"vaalea","et":"Hele on vaaleam.","fi":"Vaalea on vaaleampi.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"kõrge","finnish":"korkea","et":"Mägi on kõrge.","fi":"Vuori on korkea.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"madal","finnish":"matala","et":"Aken on madal.","fi":"Ikkuna on matala.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"paks","finnish":"paksu","et":"Raamat on paks.","fi":"Kirja on paksu.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"õhuke","finnish":"ohut","et":"Paber on õhuke.","fi":"Paperi on ohut.","cat":"adjectives","cog":0,"d":1},

  # === NUMBERS (20) ===
  {"estonian":"üks","finnish":"yksi","et":"Üks pluss üks on kaks.","fi":"Yksi plus yksi on kaksi.","cat":"numbers","cog":1,"d":1},
  {"estonian":"kaks","finnish":"kaksi","et":"Kaks pluss kaks on neli.","fi":"Kaksi plus kaksi on neljä.","cat":"numbers","cog":1,"d":1},
  {"estonian":"kolm","finnish":"kolme","et":"Kolm pluss kaks on viis.","fi":"Kolme plus kaksi on viisi.","cat":"numbers","cog":1,"d":1},
  {"estonian":"neli","finnish":"neljä","et":"Neli pluss üks on viis.","fi":"Neljä plus yksi on viisi.","cat":"numbers","cog":1,"d":1},
  {"estonian":"viis","finnish":"viisi","et":"Viis pluss viis on kümme.","fi":"Viisi plus viisi on kymmenen.","cat":"numbers","cog":1,"d":1},
  {"estonian":"kuus","finnish":"kuusi","et":"Kuus pluss kuus on kaksteist.","fi":"Kuusi plus kuusi on kaksitoista.","cat":"numbers","cog":1,"d":1},
  {"estonian":"seitse","finnish":"seitsemän","et":"Seitse pluss üks on kaheksa.","fi":"Seitsemän plus yksi on kahdeksan.","cat":"numbers","cog":0,"d":1},
  {"estonian":"kaheksa","finnish":"kahdeksan","et":"Kaheksa pluss kaks on kümme.","fi":"Kahdeksan plus kaksi on kymmenen.","cat":"numbers","cog":0,"d":1},
  {"estonian":"üheksa","finnish":"yhdeksän","et":"Üheksa pluss üks on kümme.","fi":"Yhdeksän plus yksi on kymmenen.","cat":"numbers","cog":0,"d":1},
  {"estonian":"kümme","finnish":"kymmenen","et":"Kümme pluss kümme on kakskümmend.","fi":"Kymmenen plus kymmenen on kaksikymmentä.","cat":"numbers","cog":0,"d":1},
  {"estonian":"kakskümmend","finnish":"kaksikymmentä","et":"Kakskümmend on palju.","fi":"Kaksikymmentä on paljon.","cat":"numbers","cog":0,"d":1},
  {"estonian":"kolmkümmend","finnish":"kolmekymmentä","et":"Kolmkümmend on 30.","fi":"Kolmekymmentä on 30.","cat":"numbers","cog":0,"d":1},
  {"estonian":"nelikümmend","finnish":"neljäkymmentä","et":"Nelikümmend on 40.","fi":"Neljäkymmentä on 40.","cat":"numbers","cog":0,"d":1},
  {"estonian":"viiskümmend","finnish":"viisikymmentä","et":"Viiskümmend on 50.","fi":"Viisikymmentä on 50.","cat":"numbers","cog":0,"d":1},
  {"estonian":"kuuskümmend","finnish":"kuusikymmentä","et":"Kuuskümmend on 60.","fi":"Kuusikymmentä on 60.","cat":"numbers","cog":0,"d":1},
  {"estonian":"seitsekümmend","finnish":"seitsemänkymmentä","et":"Seitsekümmend on 70.","fi":"Seitsemänkymmentä on 70.","cat":"numbers","cog":0,"d":1},
  {"estonian":"kaheksakümmend","finnish":"kahdeksankymmentä","et":"Kaheksakümmend on 80.","fi":"Kahdeksankymmentä on 80.","cat":"numbers","cog":0,"d":1},
  {"estonian":"üheksakümmend","finnish":"yhdeksänkymmentä","et":"Üheksakümmend on 90.","fi":"Yhdeksänkymmentä on 90.","cat":"numbers","cog":0,"d":1},
  {"estonian":"sada","finnish":"sata","et":"Sada on palju.","fi":"Sata on paljon.","cat":"numbers","cog":1,"d":1},
  {"estonian":"tuhat","finnish":"tuhat","et":"Tuhat on 1000.","fi":"Tuhat on 1000.","cat":"numbers","cog":1,"d":1},

  # === TIME (20) ===
  {"estonian":"täna","finnish":"tänään","et":"Täna on ilus päev.","fi":"Tänään on kaunis päivä.","cat":"time","cog":0,"d":1},
  {"estonian":"homme","finnish":"huomenna","et":"Homme on uus päev.","fi":"Huomenna on uusi päivä.","cat":"time","cog":0,"d":1},
  {"estonian":"eile","finnish":"eilen","et":"Eile oli külm.","fi":"Eilen oli kylmä.","cat":"time","cog":0,"d":1},
  {"estonian":"praegu","finnish":"nyt","et":"Praegu on külm.","fi":"Nyt on kylmä.","cat":"time","cog":1,"d":1},
  {"estonian":"varsti","finnish":"pian","et":"Varsti on talv.","fi":"Pian on talvi.","cat":"time","cog":0,"d":1},
  {"estonian":"hilja","finnish":"myöhään","et":"Hilja on jäänud.","fi":"On jäänyt myöhään.","cat":"time","cog":0,"d":1},
  {"estonian":"hommik","finnish":"aamu","et":"Hommik on vara.","fi":"Aamu on aika.","cat":"time","cog":0,"d":1},
  {"estonian":"õhtu","finnish":"ilta","et":"Õhtu on pime.","fi":"Ilta on pimeä.","cat":"time","cog":0,"d":1},
  {"estonian":"öö","finnish":"yö","et":"Öö on pime.","fi":"Yö on pimeä.","cat":"time","cog":0,"d":1},
  {"estonian":"päev","finnish":"päivä","et":"Päev on pikk.","fi":"Päivä on lyhyt.","cat":"time","cog":0,"d":1},
  {"estonian":"nädal","finnish":"viikko","et":"Nädal on pikk.","fi":"Viikko on lyhyt.","cat":"time","cog":0,"d":1},
  {"estonian":"kuu","finnish":"kuukausi","et":"Kuu on lühike.","fi":"Kuukausi on lyhyt.","cat":"time","cog":0,"d":1},
  {"estonian":"aasta","finnish":"vuosi","et":"Aasta on pikk.","fi":"Vuosi on pitkä.","cat":"time","cog":0,"d":1},
  {"estonian":"ajalugu","finnish":"historia","et":"Ajalugu on pikk.","fi":"Historia on pitkä.","cat":"time","cog":0,"d":1},
  {"estonian":"tulevik","finnish":"tulevaisuus","et":"Tulevik on hele.","fi":"Tulevaisuus on kirkas.","cat":"time","cog":0,"d":1},
  {"estonian":"eelmine","finnish":"edellinen","et":"Eelmine päev oli külm.","fi":"Edellinen päivä oli kylmä.","cat":"time","cog":0,"d":2},
  {"estonian":"järgmine","finnish":"seuraava","et":"Järgmine nädal on täis.","fi":"Seuraava viikko on täynnä.","cat":"time","cog":0,"d":1},
  {"estonian":"iga","finnish":"joka","et":"Iga päev on uus.","fi":"Joka päivä on uusi.","cat":"time","cog":0,"d":1},
  {"estonian":"kord","finnish":"kerta","et":"See on esimene kord.","fi":"Tämä on ensimmäinen kerta.","cat":"time","cog":0,"d":1},
  {"estonian":"korduma","finnish":"toistua","et":"See kordub.","fi":"Tämä toistuu.","cat":"time","cog":0,"d":2},

  # === BODY & HEALTH (20) ===
  {"estonian":"pea","finnish":"pää","et":"Pea on valutab.","fi":"Pää sattuu.","cat":"body","cog":1,"d":1},
  {"estonian":"käsi","finnish":"käsi","et":"Käsi on külm.","fi":"Käsi on kylmä.","cat":"body","cog":1,"d":1},
  {"estonian":"jalg","finnish":"jalka","et":"Jalg on valus.","fi":"Jalka on kipu.","cat":"body","cog":0,"d":1},
  {"estonian":"süda","finnish":"sydän","et":"Süda lööb.","fi":"Sydän lyö.","cat":"body","cog":0,"d":1},
  {"estonian":"kõht","finnish":"vatsa","et":"Kõht on täis.","fi":"Vatsa on täynnä.","cat":"body","cog":0,"d":1},
  {"estonian":"selg","finnish":"selkä","et":"Selg on valus.","fi":"Selkä sattuu.","cat":"body","cog":0,"d":1},
  {"estonian":"kael","finnish":"kaula","et":"Kael on külm.","fi":"Kaula on kylmä.","cat":"body","cog":0,"d":1},
  {"estonian":"sõber","finnish":"ystävä","et":"Sõber on hea.","fi":"Ystävä on hyvä.","cat":"body","cog":0,"d":1},
  {"estonian":"haige","finnish":"sairas","et":"Ma olen haige.","fi":"Olen sairas.","cat":"body","cog":0,"d":1},
  {"estonian":"terve","finnish":"terve","et":"Ma olen terve.","fi":"Olen terve.","cat":"body","cog":1,"d":1},
  {"estonian":"valus","finnish":"kivulias","et":"See on valus.","fi":"Tämä on kivulias.","cat":"body","cog":0,"d":1},
  {"estonian":"kuum","finnish":"kuume","et":"Kuum on olemas.","fi":"Kuume on olemassa.","cat":"body","cog":0,"d":1},
  {"estonian":"külm","finnish":"kylmä","et":"Külm on olemas.","fi":"Kylmä on olemassa.","cat":"body","cog":0,"d":1},
  {"estonian":"nägu","finnish":"kasvot","et":"Nägu on ilus.","fi":"Kasvot ovat kauniit.","cat":"body","cog":0,"d":1},
  {"estonian":"silm","finnish":"silmä","et":"Silm on sinine.","fi":"Silmä on sininen.","cat":"body","cog":0,"d":1},
  {"estonian":"kõrv","finnish":"korva","et":"Kõrv on tugev.","fi":"Korva on vahva.","cat":"body","cog":0,"d":1},
  {"estonian":"suu","finnish":"suu","et":"Suu on suur.","fi":"Suu on suuri.","cat":"body","cog":1,"d":1},
  {"estonian":"hammas","finnish":"hammas","et":"Hammas on valus.","fi":"Hammas sattuu.","cat":"body","cog":1,"d":1},
  {"estonian":"keel","finnish":"kieli","et":"Keel on tugev.","fi":"Kieli on vahva.","cat":"body","cog":0,"d":1},
  {"estonian":"lõug","finnish":"leuka","et":"Lõug on paks.","fi":"Leuka on paksu.","cat":"body","cog":0,"d":1},

  # === FOOD & DRINK (20) ===
  {"estonian":"vesi","finnish":"vesi","et":"Vesi on külm.","fi":"Vesi on kylmä.","cat":"food","cog":1,"d":1},
  {"estonian":"leib","finnish":"leipä","et":"Leib on värske.","fi":"Leipä on tuore.","cat":"food","cog":1,"d":1},
  {"estonian":"piim","finnish":"maito","et":"Piim on valge.","fi":"Maito on valkoinen.","cat":"food","cog":0,"d":1},
  {"estonian":"juust","finnish":"juusto","et":"Juust on kollane.","fi":"Juusto on keltainen.","cat":"food","cog":0,"d":1},
  {"estonian":"liha","finnish":"liha","et":"Liha on punane.","fi":"Liha on punainen.","cat":"food","cog":1,"d":1},
  {"estonian":"kala","finnish":"kala","et":"Kala on väike.","fi":"Kala on pieni.","cat":"food","cog":1,"d":1},
  {"estonian":"õun","finnish":"omena","et":"Õun on punane.","fi":"Omena on punainen.","cat":"food","cog":0,"d":1},
  {"estonian":"banaan","finnish":"banaani","et":"Banaan on kollane.","fi":"Banaani on keltainen.","cat":"food","cog":0,"d":1},
  {"estonian":"kartul","finnish":"peruna","et":"Kartul on suur.","fi":"Peruna on suuri.","cat":"food","cog":0,"d":1},
  {"estonian":"tomatt","finnish":"tomaatti","et":"Tomatt on punane.","fi":"Tomaatti on punainen.","cat":"food","cog":0,"d":1},
  {"estonian":"kohv","finnish":"kahvi","et":"Kohv on must.","fi":"Kahvi on musta.","cat":"food","cog":0,"d":1},
  {"estonian":"tee","finnish":"tee","et":"Tee on kuum.","fi":"Tee on kuuma.","cat":"food","cog":1,"d":1},
  {"estonian":"suhkur","finnish":"sokeri","et":"Suhkur on magus.","fi":"Sokeri on makea.","cat":"food","cog":0,"d":1},
  {"estonian":"sool","finnish":"suola","et":"Sool on soolane.","fi":"Suola on suolainen.","cat":"food","cog":0,"d":1},
  {"estonian":"õli","finnish":"öljy","et":"Õli on kollane.","fi":"Öljy on keltainen.","cat":"food","cog":0,"d":1},
  {"estonian":"jää","finnish":"jää","et":"Jää on külm.","fi":"Jää on kylmä.","cat":"food","cog":1,"d":1},
  {"estonian":"kook","finnish":"kakku","et":"Kook on magus.","fi":"Kakku on makea.","cat":"food","cog":0,"d":1},
  {"estonian":"supp","finnish":"keitto","et":"Supp on soe.","fi":"Keitto on lämmin.","cat":"food","cog":0,"d":1},
  {"estonian":"salat","finnish":"salaatti","et":"Salat on roheline.","fi":"Salaatti on vihreä.","cat":"food","cog":0,"d":1},
  {"estonian":"pitsa","finnish":"pizza","et":"Pitsa on soe.","fi":"Pizza on lämmin.","cat":"food","cog":0,"d":1},

  # === NATURE & WEATHER (20) ===
  {"estonian":"päike","finnish":"aurinko","et":"Päike paistab.","fi":"Aurinko paistaa.","cat":"nature","cog":0,"d":1},
  {"estonian":"kuu","finnish":"kuu","et":"Kuu on hele.","fi":"Kuu on kirkas.","cat":"nature","cog":1,"d":1},
  {"estonian":"täht","finnish":"tähti","et":"Taevas on palju tähti.","fi":"Taivaalla on paljon tähtiä.","cat":"nature","cog":0,"d":1},
  {"estonian":"pilv","finnish":"pilvi","et":"Pilved on valged.","fi":"Pilvet ovat valkoisia.","cat":"nature","cog":0,"d":1},
  {"estonian":"vihm","finnish":"sade","et":"Sata vihma.","fi":"Sata sadetta.","cat":"nature","cog":0,"d":1},
  {"estonian":"lumi","finnish":"lumi","et":"Lumi on valge.","fi":"Lumi on valkoinen.","cat":"nature","cog":1,"d":1},
  {"estonian":"tuul","finnish":"tuuli","et":"Tuul puhub.","fi":"Tuuli puhuu.","cat":"nature","cog":1,"d":1},
  {"estonian":"meri","finnish":"meri","et":"Meri on sinine.","fi":"Meri on sininen.","cat":"nature","cog":1,"d":1},
  {"estonian":"jõgi","finnish":"joki","et":"Jõgi voolab.","fi":"Joki virtaa.","cat":"nature","cog":0,"d":1},
  {"estonian":"mets","finnish":"metsä","et":"Mets on roheline.","fi":"Metsä on vihreä.","cat":"nature","cog":0,"d":1},
  {"estonian":"kallas","finnish":"rannikko","et":"Kallas on ilus.","fi":"Rannikko on kaunis.","cat":"nature","cog":0,"d":2},
  {"estonian":"saar","finnish":"saari","et":"Saar on väike.","fi":"Saari on pieni.","cat":"nature","cog":0,"d":1},
  {"estonian":"mägi","finnish":"vuori","et":"Mägi on kõrge.","fi":"Vuori on korkea.","cat":"nature","cog":0,"d":1},
  {"estonian":"org","finnish":"laakso","et":"Org on lai.","fi":"Laakso on laaja.","cat":"nature","cog":0,"d":2},
  {"estonian":"torm","finnish":"myrsky","et":"Torm on tugev.","fi":"Myrsky on voimakas.","cat":"nature","cog":0,"d":2},
  {"estonian":"äike","finnish":"salama","et":"Äike kõlab.","fi":"Salama jyskyy.","cat":"nature","cog":0,"d":2},
  {"estonian":"vikerkaar","finnish":"sateenkaari","et":"Vikerkaar on ilus.","fi":"Sateenkaari on kaunis.","cat":"nature","cog":0,"d":2},
  {"estonian":"hõbe","finnish":"hopea","et":"Hõbe on hele.","fi":"Hopea on vaalea.","cat":"nature","cog":1,"d":1},
  {"estonian":"kuld","finnish":"kulta","et":"Kuld on kollane.","fi":"Kulta on keltainen.","cat":"nature","cog":1,"d":1},
  {"estonian":"tuli","finnish":"tuli","et":"Tuli on kuum.","fi":"Tuli on kuuma.","cat":"nature","cog":1,"d":1},

  # === HOME & FURNITURE (20) ===
  {"estonian":"maja","finnish":"talo","et":"Maja on suur.","fi":"Talo on suuri.","cat":"home","cog":0,"d":1},
  {"estonian":"kodu","finnish":"koti","et":"Kodu on soe.","fi":"Koti on lämmin.","cat":"home","cog":0,"d":1},
  {"estonian":"tuba","finnish":"huone","et":"Tuba on suur.","fi":"Huone on suuri.","cat":"home","cog":0,"d":1},
  {"estonian":"voodi","finnish":"sänky","et":"Voodi on mugav.","fi":"Sänky on mukava.","cat":"home","cog":0,"d":1},
  {"estonian":"laud","finnish":"pöytä","et":"Laud on lai.","fi":"Pöytä on laaja.","cat":"home","cog":0,"d":1},
  {"estonian":"tool","finnish":"tuoli","et":"Tool on mugav.","fi":"Tuoli on mukava.","cat":"home","cog":0,"d":1},
  {"estonian":"kapp","finnish":"kaappi","et":"Kapp on suur.","fi":"Kaappi on suuri.","cat":"home","cog":0,"d":1},
  {"estonian":"peegel","finnish":"peili","et":"Peegel on selge.","fi":"Peili on selkeä.","cat":"home","cog":0,"d":1},
  {"estonian":"küünal","finnish":"kynttilä","et":"Küünal on põlemas.","fi":"Kynttilä on palaa.","cat":"home","cog":0,"d":1},
  {"estonian":"põrand","finnish":"lattia","et":"Põrand on puhas.","fi":"Lattia on puhdas.","cat":"home","cog":0,"d":1},
  {"estonian":"lagi","finnish":"katos","et":"Lagi on uus.","fi":"Katos on uusi.","cat":"home","cog":0,"d":1},
  {"estonian":"sein","finnish":"seinä","et":"Sein on valge.","fi":"Seinä on valkoinen.","cat":"home","cog":0,"d":1},
  {"estonian":"uks","finnish":"ovi","et":"Uks on tugev.","fi":"Ovi on vahva.","cat":"home","cog":0,"d":1},
  {"estonian":"aken","finnish":"ikkuna","et":"Aken on suur.","fi":"Ikkuna on suuri.","cat":"home","cog":0,"d":1},
  {"estonian":"kamin","finnish":"takka","et":"Kamin on soe.","fi":"Takka on lämmin.","cat":"home","cog":0,"d":1},
  {"estonian":"ventilaator","finnish":"tuuletin","et":"Ventilaator on kõrge.","fi":"Tuuletin on korkea.","cat":"home","cog":0,"d":2},
  {"estonian":"tekk","finnish":"patja","et":"Tekk on pehme.","fi":"Patja on pehmeä.","cat":"home","cog":0,"d":1},
  {"estonian":"diivan","finnish":"sohva","et":"Diivan on mugav.","fi":"Sohva on mukava.","cat":"home","cog":0,"d":1},
  {"estonian":"kardin","finnish":"verho","et":"Kardin on paks.","fi":"Verho on paksu.","cat":"home","cog":0,"d":1},
  {"estonian":"pärand","finnish":"perinne","et":"Pärand on väärtuslik.","fi":"Perinne on arvokas.","cat":"home","cog":0,"d":2},

  # === WORK & PROFESSIONS (20) ===
  {"estonian":"töö","finnish":"työ","et":"Töö on vajalik.","fi":"Työ on tarpeen.","cat":"work","cog":1,"d":1},
  {"estonian":"õpetaja","finnish":"opettaja","et":"Õpetaja on tark.","fi":"Opettaja on älykäs.","cat":"work","cog":0,"d":1},
  {"estonian":"arst","finnish":"lääkäri","et":"Arst on tark.","fi":"Lääkäri on älykäs.","cat":"work","cog":0,"d":1},
  {"estonian":"müüja","finnish":"myyjä","et":"Müüja on sõbralik.","fi":"Myyjä on ystävällinen.","cat":"work","cog":0,"d":1},
  {"estonian":"kokk","finnish":"kokki","et":"Kokk on oskuslik.","fi":"Kokki on taitava.","cat":"work","cog":0,"d":1},
  {"estonian":"juht","finnish":"johtaja","et":"Juht on tark.","fi":"Johtaja on älykäs.","cat":"work","cog":0,"d":1},
  {"estonian":"insener","finnish":"insinööri","et":"Insener on tark.","fi":"Insinööri on älykäs.","cat":"work","cog":0,"d":1},
  {"estonian":"arhitekt","finnish":"arkkitehti","et":"Arhitekt on loominguline.","fi":"Arkkitehti on luova.","cat":"work","cog":0,"d":2},
  {"estonian":"advokaat","finnish":"asianajaja","et":"Advokaat on tark.","fi":"Asianajaja on älykäs.","cat":"work","cog":0,"d":2},
  {"estonian":"proua","finnish":"rouva","et":"Proua on austav.","fi":"Rouva on kunnioitettava.","cat":"work","cog":0,"d":2},
  {"estonian":"härra","finnish":"herra","et":"Härra on austav.","fi":"Herra on kunnioitettava.","cat":"work","cog":0,"d":2},
  {"estonian":"neiu","finnish":"neiti","et":"Neiu on noor.","fi":"Neiti on nuori.","cat":"work","cog":0,"d":1},
  {"estonian":"poisike","finnish":"poika","et":"Poisike on väike.","fi":"Poika on pieni.","cat":"work","cog":0,"d":1},
  {"estonian":"tüdruk","finnish":"tyttö","et":"Tüdruk on ilus.","fi":"Tyttö on kaunis.","cat":"work","cog":0,"d":1},
  {"estonian":"mees","finnish":"mies","et":"Mees on tugev.","fi":"Mies on vahva.","cat":"work","cog":0,"d":1},
  {"estonian":"naine","finnish":"nainen","et":"Naine on tark.","fi":"Nainen on älykäs.","cat":"work","cog":0,"d":1},
  {"estonian":"laps","finnish":"lapsi","et":"Laps on väike.","fi":"Lapsi on pieni.","cat":"work","cog":0,"d":1},
  {"estonian":"sõber","finnish":"ystävä","et":"Sõber on hea.","fi":"Ystävä on hyvä.","cat":"work","cog":0,"d":1},
  {"estonian":"perekond","finnish":"perhe","et":"Perekond on suur.","fi":"Perhe on suuri.","cat":"work","cog":0,"d":1},
  {"estonian":"kolleeg","finnish":"työtoveri","et":"Kolleeg on sõbralik.","fi":"Työtoveri on ystävällinen.","cat":"work","cog":0,"d":2},

  # === SOCIETY & CONNECTORS (20) ===
  {"estonian":"ja","finnish":"ja","et":"Mina ja sina.","fi":"Minä ja sinä.","cat":"connectors","cog":1,"d":1},
  {"estonian":"või","finnish":"tai","et":"Kas või kohv?","fi":"Kahvi tai tee?","cat":"connectors","cog":0,"d":1},
  {"estonian":"aga","finnish":"mutta","et":"Ma tahan, aga ma ei saa.","fi":"Haluan, mutta en saa.","cat":"connectors","cog":0,"d":1},
  {"estonian":"sest","finnish":"koska","et":"Ma ei tule, sest ma olen haige.","fi":"En tule, koska olen sairas.","cat":"connectors","cog":0,"d":2},
  {"estonian":"kui","finnish":"kun","et":"Kui ma tulen, ma helistan.","fi":"Kun tulen, soitan.","cat":"connectors","cog":0,"d":1},
  {"estonian":"et","finnish":"että","et":"Ma tean, et sa tuled.","fi":"Tiedän, että tulet.","cat":"connectors","cog":0,"d":1},
  {"estonian":"kui ka","finnish":"myös","et":"Ma kui ka sina.","fi":"Minä ja sinä myös.","cat":"connectors","cog":0,"d":1},
  {"estonian":"vaid","finnish":"vain","et":"Ma tahan vaid head.","fi":"Haluan vain hyvää.","cat":"connectors","cog":0,"d":1},
  {"estonian":"ka","finnish":"myös","et":"Ka mina.","fi":"Myös minä.","cat":"connectors","cog":0,"d":1},
  {"estonian":"ikka","finnish":"aina","et":"Ma ikka armastan.","fi":"Minä aina rakastan.","cat":"connectors","cog":0,"d":1},
  {"estonian":"juba","finnish":"jo","et":"See on juba valmis.","fi":"Tämä on jo valmis.","cat":"connectors","cog":0,"d":1},
  {"estonian":"veel","finnish":"vielä","et":"Ma olen veel siin.","fi":"Olen vielä täällä.","cat":"connectors","cog":0,"d":1},
  {"estonian":"ära","finnish":"älä","et":"Ära tee seda!","fi":"Älä tee sitä!","cat":"connectors","cog":0,"d":1},
  {"estonian":"palun","finnish":"kiitos","et":"Palun!","fi":"Ole hyvä!","cat":"connectors","cog":0,"d":1},
  {"estonian":"vabandust","finnish":"anteeksi","et":"Vabandust!","fi":"Anteeksi!","cat":"connectors","cog":0,"d":1},
  {"estonian":"tere","finnish":"hei","et":"Tere!","fi":"Hei!","cat":"connectors","cog":1,"d":1},
  {"estonian":"head aega","finnish":"hyvää matkaa","et":"Head aega!","fi":"Hyvää matkaa!","cat":"connectors","cog":0,"d":1},
  {"estonian":"palju õnne","finnish":"paljon onnea","et":"Palju õnne!","fi":"Paljon onnea!","cat":"connectors","cog":0,"d":1},
  {"estonian":"õnnitle","finnish":"onnittele","et":"Õnnitle mind!","fi":"Onnittele minua!","cat":"connectors","cog":0,"d":1},
  {"estonian":"võta heaks","finnish":"ota vastaan","et":"Võta heaks!","fi":"Ota vastaan!","cat":"connectors","cog":0,"d":2},

  # === MULTI-WORD EXPRESSIONS (20) ===
  {"estonian":"kuidas läheb","finnish":"miten menee","et":"Kuidas läheb?","fi":"Miten menee?","cat":"phrases","cog":0,"d":1},
  {"estonian":"mis toimub","finnish":"mitä tapahtuu","et":"Mis toimub?","fi":"Mitä tapahtuu?","cat":"phrases","cog":0,"d":1},
  {"estonian":"kellele","finnish":"kenelle","et":"Kellele sa annad?","fi":"Kenelle annat?","cat":"phrases","cog":0,"d":1},
  {"estonian":"miks","finnish":"miksi","et":"Miks sa tulid?","fi":"Miksi tulit?","cat":"phrases","cog":0,"d":1},
  {"estonian":"millal","finnish":"milloin","et":"Millal sa tuled?","fi":"Milloin tulet?","cat":"phrases","cog":0,"d":1},
  {"estonian":"kus","finnish":"missä","et":"Kus sa oled?","fi":"Missä olet?","cat":"phrases","cog":0,"d":1},
  {"estonian":"kust","finnish":"mistä","et":"Kust sa tuled?","fi":"Mistä tulet?","cat":"phrases","cog":0,"d":1},
  {"estonian":"kuhu","finnish":"minne","et":"Kuhu sa lähed?","fi":"Minne menet?","cat":"phrases","cog":0,"d":1},
  {"estonian":"kumb","finnish":"kumpi","et":"Kumb on parem?","fi":"Kumpi on parempi?","cat":"phrases","cog":0,"d":1},
  {"estonian":"mitte","finnish":"ei","et":"Mitte nii.","fi":"Ei niin.","cat":"phrases","cog":0,"d":1},
  {"estonian":"rohkem","finnish":"enemmän","et":"Rohkem head.","fi":"Enemmän hyvää.","cat":"phrases","cog":0,"d":1},
  {"estonian":"vähem","finnish":"vähemmän","et":"Vähem halb.","fi":"Vähemmän huonoa.","cat":"phrases","cog":0,"d":1},
  {"estonian":"kõige","finnish":"kaikkein","et":"Kõige parem.","fi":"Kaikkein paras.","cat":"phrases","cog":0,"d":1},
  {"estonian":"üldse","finnish":"ollenkaan","et":"Üldse ei.","fi":"Ei ollenkaan.","cat":"phrases","cog":0,"d":1},
  {"estonian":"just nüüd","finnish":"juuri nyt","et":"Just nüüd.","fi":"Juuri nyt.","cat":"phrases","cog":0,"d":1},
  {"estonian":"homme vara","finnish":"huomenna aamulla","et":"Homme vara.","fi":"Huomenna aamulla.","cat":"phrases","cog":0,"d":1},
  {"estonian":"eelmine aasta","finnish":"viime vuosi","et":"Eelmine aasta.","fi":"Viime vuosi.","cat":"phrases","cog":0,"d":1},
  {"estonian":"järgmine kord","finnish":"seuraava kerta","et":"Järgmine kord.","fi":"Seuraava kerta.","cat":"phrases","cog":0,"d":1},
  {"estonian":"praegu","finnish":"juuri nyt","et":"Praegu on külm.","fi":"Juuri nyt on kylmä.","cat":"phrases","cog":0,"d":1},
  {"estonian":"varsti","finnish":"pian","et":"Varsti on talv.","fi":"Pian on talvi.","cat":"phrases","cog":0,"d":1},
]
