"""Seed Part 3: Transport & Travel (40 words)"""
SEED_PART3 = [
  {"estonian":"auto","finnish":"auto","et":"Auto on uus.","fi":"Auto on uusi.","cat":"transport","cog":1,"d":1},
  {"estonian":"buss","finnish":"bussi","et":"Buss tuleb viie minuti pärast.","fi":"Bussi tulee viiden minuutin päästä.","cat":"transport","cog":1,"d":1},
  {"estonian":"rong","finnish":"juna","et":"Rong läheb Helsingisse.","fi":"Juna menee Helsinkiin.","cat":"transport","cog":0,"d":1},
  {"estonian":"lennuk","finnish":"lentokone","et":"Lennuk on hilinenud.","fi":"Lentokone on myöhässä.","cat":"transport","cog":0,"d":2},
  {"estonian":"laev","finnish":"laiva","et":"Laev sõidab Tallinnast Helsinki.","fi":"Laivailee Tallinnasta Helsinkiin.","cat":"transport","cog":0,"d":1},
  {"estonian":"ratas","finnish":"polkupyörä","et":"Ratas on punane.","fi":"Polkupyörä on punainen.","cat":"transport","cog":0,"d":2},
  {"estonian":"takso","finnish":"taksi","et":"Kutsu takso!","fi":"Soita taksi!","cat":"transport","cog":1,"d":1},
  {"estonian":"peatus","finnish":"pysäkki","et":"Peatus on siin.","fi":"Pysäkki on täällä.","cat":"transport","cog":0,"d":2},
  {"estonian":"pilet","finnish":"lippu","et":"Kus ma saan pileti?","fi":"Mistä saan lipun?","cat":"transport","cog":0,"d":1},
  {"estonian":"sõita","finnish":"ajaa","et":"Ma sõidan autoga.","fi":"Minä ajan autolla.","cat":"transport","cog":0,"d":2},
  {"estonian":"minema","finnish":"mennä","et":"Kuhu sa lähed?","fi":"Minne sinä menet?","cat":"transport","cog":0,"d":1},
  {"estonian":"tulema","finnish":"tulla","et":"Millal sa tuled?","fi":"Milloin sinä tulet?","cat":"transport","cog":0,"d":1},
  {"estonian":"jooksma","finnish":"juosta","et":"Ma jooksin bussi ära.","fi":"Juoksin bussin ohi.","cat":"transport","cog":0,"d":2},
  {"estonian":"ootama","finnish":"odottaa","et":"Ma ootan bussi.","fi":"Minä odotan bussia.","cat":"transport","cog":0,"d":2},
  {"estonian":"sihtkoht","finnish":"määränpää","et":"Mis on su sihtkoht?","fi":"Mikä on määränpääsi?","cat":"transport","cog":0,"d":3},
  {"estonian":"reis","finnish":"matka","et":"Head reisi!","fi":"Hyvää matkaa!","cat":"transport","cog":0,"d":1},
  {"estonian":"pass","finnish":"passi","et":"Kus on mu pass?","fi":"Missä on passini?","cat":"transport","cog":1,"d":1},
  {"estonian":"visa","finnish":"viisumi","et":"Kas sul on visa?","fi":"Onko sinulla viisumia?","cat":"transport","cog":0,"d":2},
  {"estonian":"lennujaam","finnish":"lentokenttä","et":"Lennujaam on kaugel.","fi":"Lentokenttä on kaukana.","cat":"transport","cog":0,"d":2},
  {"estonian":"jaam","finnish":"asema","et":"Rongijaam on siin.","fi":"Junasema on täällä.","cat":"transport","cog":0,"d":1},
  {"estonian":"sõidukaart","finnish":"kortti","et":"Kus ma saan sõidukaardi?","fi":"Mistä saan kortin?","cat":"transport","cog":0,"d":2},
  {"estonian":"kiirtee","finnish":"moottoritie","et":"Kiirtee on kiire.","fi":"Moottoritie on nopea.","cat":"transport","cog":0,"d":3},
  {"estonian":"teel","finnish":"tiellä","et":"Teel on palju autosid.","fi":"Tiellä on paljon autoja.","cat":"transport","cog":0,"d":2},
  {"estonian":"parkida","finnish":"pysäköidä","et":"Kus ma saan parkida?","fi":"Minne voin pysäköidä?","cat":"transport","cog":0,"d":2},
  {"estonian":"pidur","finnish":"jarru","et":"Pidur ei tööta.","fi":"Jarru ei toimi.","cat":"transport","cog":0,"d":2},
  {"estonian":"rool","finnish":"ratti","et":"Istu rooli!","fi":"Istu rattaille!","cat":"transport","cog":0,"d":2},
  {"estonian":"mootor","finnish":"moottori","et":"Mootor on käivitunud.","fi":"Moottori on käynnistynyt.","cat":"transport","cog":0,"d":2},
  {"estonian":"kütus","finnish":"polttoaine","et":"Kütus on otsas.","fi":"Polttoaine on lopussa.","cat":"transport","cog":0,"d":3},
  {"estonian":"rehvid","finnish":"renkaat","et":"Rehvid on tühjad.","fi":"Renkaat ovat tyhjät.","cat":"transport","cog":0,"d":2},
  {"estonian":"kiirus","finnish":"nopeus","et":"Kiirus on liiga suur.","fi":"Nopeus on liian suuri.","cat":"transport","cog":0,"d":2},
  {"estonian":"liiklus","finnish":"liikenne","et":"Liiklus on tihe.","fi":"Liikenne on tiheä.","cat":"transport","cog":0,"d":2},
  {"estonian":"ummik","finnish":"ruuhka","et":"Ummik on suur.","fi":"Ruuhka on suuri.","cat":"transport","cog":0,"d":2},
  {"estonian":"teerist","finnish":"risteys","et":"Pööra teerist paremale.","fi":"Käänny risteyksessä oikealle.","cat":"transport","cog":0,"d":3},
  {"estonian":"parkla","finnish":"parkkialue","et":"Parkla on täis.","fi":"Parkkialue on täynnä.","cat":"transport","cog":0,"d":2},
  {"estonian":"garaaž","finnish":"autotalli","et":"Auto on garaažis.","fi":"Auto on autotallissa.","cat":"transport","cog":0,"d":2},
  {"estonian":"remont","finnish":"korjaus","et":"Auto on remondis.","fi":"Auto on korjauksessa.","cat":"transport","cog":0,"d":2},
  {"estonian":"kindlustus","finnish":"vakuutus","et":"Kas sul on kindlustus?","fi":"Onko sinulla vakuutusta?","cat":"transport","cog":0,"d":3},
  {"estonian":"number","finnish":"numero","et":"Mis on su telefoninumber?","fi":"Mikä on puhelinnumerosi?","cat":"transport","cog":0,"d":1},
  {"estonian":"aadress","finnish":"osoite","et":"Mis on su aadress?","fi":"Mikä on osoitteesi?","cat":"transport","cog":0,"d":1},
  {"estonian":"kaart","finnish":"kartta","et":"Kus on kaart?","fi":"Missä on kartta?","cat":"transport","cog":0,"d":1},
]
