"""Seed Part 6: Home & Time (40 words)"""
SEED_PART6 = [
  {"estonian":"kodu","finnish":"koti","et":"Ma lähen koju.","fi":"Menemme kotiin.","cat":"home","cog":0,"d":1},
  {"estonian":"maja","finnish":"talo","et":"Maja on suur.","fi":"Talo on suuri.","cat":"home","cog":0,"d":1},
  {"estonian":"tuba","finnish":"huone","et":"Tuba on soe.","fi":"Huone on lämmin.","cat":"home","cog":0,"d":1},
  {"estonian":"köök","finnish":"keittiö","et":"Köök on väike.","fi":"Keittiö on pieni.","cat":"home","cog":0,"d":1},
  {"estonian":"magamistuba","finnish":"makuuhuone","et":"Magamistuba on ülal.","fi":"Makuuhuone on yläällä.","cat":"home","cog":0,"d":2},
  {"estonian":"vannituba","finnish":"kylpyhuone","et":"Vannituba on uus.","fi":"Kylpyhuone on uusi.","cat":"home","cog":0,"d":2},
  {"estonian":"elutuba","finnish":"olohuone","et":"Elutuba on avar.","fi":"Olohuone on avara.","cat":"home","cog":0,"d":1},
  {"estonian":"aken","finnish":"ikkuna","et":"Aken on avatud.","fi":"Ikkuna on auki.","cat":"home","cog":0,"d":1},
  {"estonian":"uks","finnish":"ovi","et":"Uks on suletud.","fi":"Ovi on kiinni.","cat":"home","cog":0,"d":1},
  {"estonian":"lava","finnish":"pöytä","et":"Laud on suur.","fi":"Pöytä on suuri.","cat":"home","cog":0,"d":1},
  {"estonian":"tool","finnish":"tuoli","et":"Tool on mugav.","fi":"Tuoli on mukava.","cat":"home","cog":0,"d":1},
  {"estonian":"voodi","finnish":"sänky","et":"Voodi on pehme.","fi":"Sänky on pehmeä.","cat":"home","cog":0,"d":1},
  {"estonian":"matt","finnish":"patja","et":"Matt on soe.","fi":"Patja on lämmin.","cat":"home","cog":0,"d":1},
  {"estonian":"pesema","finnish":"pestä","et":"Ma pesen käsi.","fi":"Pesen käteni.","cat":"home","cog":0,"d":2},
  {"estonian":"koristama","finnish":"siivota","et":"Ma koristan tuba.","fi":"Siivoan huoneen.","cat":"home","cog":0,"d":2},
  {"estonian":"pesumasin","finnish":"pesukone","et":"Pesumasin töötab.","fi":"Pesukone toimii.","cat":"home","cog":0,"d":2},
  {"estonian":"külmkapp","finnish":"jääkaappi","et":"Külmkapp on tühi.","fi":"Jääkaappi on tyhjä.","cat":"home","cog":0,"d":2},
  {"estonian":"mikrolaine","finnish":"mikroaaltouuni","et":"Pane mikrolainesse.","fi":"Laita mikroaaltouuniin.","cat":"home","cog":0,"d":2},
  {"estonian":"pliit","finnish":"liesi","et":"Pliit on soe.","fi":"Liesi on kuuma.","cat":"home","cog":0,"d":1},
  {"estonian":"kraanikauss","finnish":"allas","et":"Kraanikauss on täis.","fi":"allas on täynnä.","cat":"home","cog":0,"d":2},
  {"estonian":"homme","finnish":"huomenna","et":"Homme on uus päev.","fi":"Huomenna on uusi päivä.","cat":"time","cog":0,"d":1},
  {"estonian":"täna","finnish":"tänään","et":"Täna on ilus päev.","fi":"Tänään on kaunis päivä.","cat":"time","cog":0,"d":1},
  {"estonian":"eile","finnish":"eilen","et":"Eile oli külm.","fi":"Eilen oli kylmä.","cat":"time","cog":0,"d":1},
  {"estonian":"nüüd","finnish":"nyt","et":"Nüüd on aeg.","fi":"Nyt on aika.","cat":"time","cog":0,"d":1},
  {"estonian":"varsti","finnish":"pian","et":"Ma tulen varsti.","fi":"Tulen pian.","cat":"time","cog":0,"d":2},
  {"estonian":"hilja","finnish":"myöhään","et":"Ma tulin hilja.","fi":"Tulin myöhään.","cat":"time","cog":0,"d":2},
  {"estonian":"varajane","finnish":"aikainen","et":"Ma olen varajane.","fi":"Olen aikainen.","cat":"time","cog":0,"d":2},
  {"estonian":"hilinemine","finnish":"myöhästyminen","et":"Ma olingi hilinenud.","fi":"Myöhästyin.","cat":"time","cog":0,"d":3},
  {"estonian":"päev","finnish":"päivä","et":"Ilus päev!","fi":"Kaunis päivä!","cat":"time","cog":0,"d":1},
  {"estonian":"öö","finnish":"yö","et":"Öö on pime.","fi":"Yö on pimeä.","cat":"time","cog":0,"d":1},
  {"estonian":"nädal","finnish":"viikko","et":"Nädal on pikk.","fi":"Viikko on lyhyt.","cat":"time","cog":0,"d":1},
  {"estonian":"kuu","finnish":"kuukausi","et":"Kuu on kallim.","fi":"Kuukausi on kallimpi.","cat":"time","cog":0,"d":1},
  {"estonian":"aasta","finnish":"vuosi","et":"Aasta on pikk.","fi":"Vuosi on pitkä.","cat":"time","cog":0,"d":1},
  {"estonian":"esmaspäev","finnish":"maanantai","et":"Esmaspäev on uus nädal.","fi":"Maanantai on uusi viikko.","cat":"time","cog":0,"d":2},
  {"estonian":"reede","finnish":"perjantai","et":"Reede on viimane päev.","fi":"Perjantai on viimeinen päivä.","cat":"time","cog":0,"d":2},
  {"estonian":"puhkepäev","finnish":"vapaapäivä","et":"Puhkepäev on ilus.","fi":"Vapaapäivä on kaunis.","cat":"time","cog":0,"d":2},
  {"estonian":"tund","finnish":"tunti","et":"Tund on läbi.","fi":"Tunti on ohi.","cat":"time","cog":0,"d":1},
  {"estonian":"minut","finnish":"minuutti","et":"Minut on lühike.","fi":"Minuutti on lyhyt.","cat":"time","cog":0,"d":1},
  {"estonian":"hommik","finnish":"aamu","et":"Hommik on varajane.","fi":"Aamu on aikainen.","cat":"time","cog":0,"d":1},
  {"estonian":"õhtu","finnish":"ilta","et":"Õhtu on ilus.","fi":"Ilta on kaunis.","cat":"time","cog":0,"d":1},
]
