"""Seed Part 8: Clothing & Nature (40 words)"""
SEED_PART8 = [
  {"estonian":"riided","finnish":"vaatteet","et":"Riided on puhtad.","fi":"Vaatteet ovat puhtaat.","cat":"clothing","cog":0,"d":1},
  {"estonian":"seelik","finnish":"housut","et":"Seelik on uus.","fi":"Housut ovat uudet.","cat":"clothing","cog":0,"d":1},
  {"estonian":"püksid","finnish":"housut","et":"Püksid on sinised.","fi":"Housut ovat siniset.","cat":"clothing","cog":0,"d":1},
  {"estonian":"särk","finnish":"paita","et":"Särk on valge.","fi":"Paita on valkoinen.","cat":"clothing","cog":0,"d":1},
  {"estonian":"kleit","finnish":"mekko","et":"Kleit on ilus.","fi":"Mekko on kaunis.","cat":"clothing","cog":0,"d":1},
  {"estonian":"müts","finnish":"hattu","et":"Müts on soe.","fi":"Hattu on lämmin.","cat":"clothing","cog":0,"d":1},
  {"estonian":"kingad","finnish":"kengät","et":"Kingad on suured.","fi":"Kengät ovat suuret.","cat":"clothing","cog":0,"d":1},
  {"estonian":"sussid","finnish":"sukat","et":"Sussid on soojad.","fi":"Sukat ovat lämpimät.","cat":"clothing","cog":0,"d":1},
  {"estonian":"kinnas","finnish":"hanska","et":"Kinnas on soe.","fi":"Hanska on lämmin.","cat":"clothing","cog":0,"d":1},
  {"estonian":"ehe","finnish":"koru","et":"Ehe on kallis.","fi":"Koru on kallis.","cat":"clothing","cog":0,"d":2},
  {"estonian":"prillid","finnish":"lasit","et":"Prillid on uued.","fi":"Lasit ovat uudet.","cat":"clothing","cog":0,"d":1},
  {"estonian":"vöö","finnish":"vyö","et":"Vöö on kitsas.","fi":"Vyö on kapea.","cat":"clothing","cog":0,"d":1},
  {"estonian":"tasku","finnish":"tasku","et":"Tasku on tühi.","fi":"Tasku on tyhjä.","cat":"clothing","cog":1,"d":1},
  {"estonian":"nööp","finnish":"nappi","et":"Nööp on ära.","fi":"Nappi on irti.","cat":"clothing","cog":0,"d":2},
  {"estonian":"tikkima","finnish":"ommella","et":"Ma tikkin uue kleidi.","fi":"Ompelin uuden mekon.","cat":"clothing","cog":0,"d":3},
  {"estonian":"puhas","finnish":"puhdas","et":"Riided on puhtad.","fi":"Vaatteet ovat puhtaat.","cat":"clothing","cog":0,"d":1},
  {"estonian":"must","finnish":"likainen","et":"Riided on mustad.","fi":"Vaatteet ovat likaiset.","cat":"clothing","cog":0,"d":1},
  {"estonian":"päike","finnish":"aurinko","et":"Päike paistab.","fi":"Aurinko paistaa.","cat":"nature","cog":0,"d":1},
  {"estonian":"kuu","finnish":"kuu","et":"Kuus on hele.","fi":"Kuu on kirkas.","cat":"nature","cog":1,"d":1},
  {"estonian":"täht","finnish":"tähti","et":"Täht on ilus.","fi":"Tähti on kaunis.","cat":"nature","cog":0,"d":1},
  {"estonian":"pilv","finnish":"pilvi","et":"Pilved on mustad.","fi":"Pilvet ovat mustat.","cat":"nature","cog":0,"d":1},
  {"estonian":"vihm","finnish":"sade","et":"Vihm sajab.","fi":"Sade sataa.","cat":"nature","cog":0,"d":1},
  {"estonian":"lumi","finnish":"lumi","et":"Lumi on valge.","fi":"Lumi on valkoinen.","cat":"nature","cog":1,"d":1},
  {"estonian":"tuul","finnish":"tuuli","et":"Tuul puhub.","fi":"Tuuli puhaltaa.","cat":"nature","cog":0,"d":1},
  {"estonian":"külm","finnish":"kylmä","et":"On väga külm.","fi":"On erittäin kylmä.","cat":"nature","cog":0,"d":1},
  {"estonian":"soe","finnish":"lämmin","et":"On väga soe.","fi":"On erittäin lämmin.","cat":"nature","cog":0,"d":1},
  {"estonian":"päev","finnish":"päivä","et":"Päev on pikk.","fi":"Päivä on lyhyt.","cat":"nature","cog":0,"d":1},
  {"estonian":"öö","finnish":"yö","et":"Öö on pime.","fi":"Yö on pimeä.","cat":"nature","cog":0,"d":1},
  {"estonian":"mets","finnish":"metsä","et":"Mets on tihe.","fi":"Metsä on tiheä.","cat":"nature","cog":0,"d":1},
  {"estonian":"järv","finnish":"järvi","et":"Järv on suur.","fi":"Järvi on suuri.","cat":"nature","cog":0,"d":1},
  {"estonian":"meri","finnish":"meri","et":"Meri on sinine.","fi":"Meri on sininen.","cat":"nature","cog":1,"d":1},
  {"estonian":"rand","finnish":"ranta","et":"Rand on ilus.","fi":"Ranta on kaunis.","cat":"nature","cog":0,"d":1},
  {"estonian":"mägi","finnish":"vuori","et":"Mägi on kõrge.","fi":"Vuori on korkea.","cat":"nature","cog":0,"d":1},
  {"estonian":"org","finnish":"laakso","et":"Org on ilus.","fi":"Laakso on kaunis.","cat":"nature","cog":0,"d":2},
  {"estonian":"puu","finnish":"puu","et":"Puu on vana.","fi":"Puu on vanha.","cat":"nature","cog":1,"d":1},
  {"estonian":"lill","finnish":"kukka","et":"Lill on ilus.","fi":"Kukka on kaunis.","cat":"nature","cog":0,"d":1},
  {"estonian":"rohi","finnish":"ruoho","et":"Rohi on roheline.","fi":"Ruoho on vihreä.","cat":"nature","cog":0,"d":1},
  {"estonian":"lind","finnish":"lintu","et":"Lind lendab.","fi":"Lintu lentää.","cat":"nature","cog":0,"d":1},
  {"estonian":"koer","finnish":"koira","et":"Koer haugub.","fi":"Koira haukkuu.","cat":"nature","cog":0,"d":1},
  {"estonian":"kass","finnish":"kissa","et":"Kass norskab.","fi":"Kissa nukkuu.","cat":"nature","cog":0,"d":1},
]
