"""Seed Part 7: Communication & People (40 words)"""
SEED_PART7 = [
  {"estonian":"sõber","finnish":"ystävä","et":"See on mu sõber.","fi":"Tämä on ystäväni.","cat":"people","cog":0,"d":1},
  {"estonian":"perekond","finnish":"perhe","et":"Mu perekond on suur.","fi":"Perheeni on suuri.","cat":"people","cog":0,"d":1},
  {"estonian":"isa","finnish":"isä","et":"Mu isa on tark.","fi":"Isäni on viisas.","cat":"people","cog":0,"d":1},
  {"estonian":"ema","finnish":"äiti","et":"Mu emu on hea.","fi":"Äitini on hyvä.","cat":"people","cog":0,"d":1},
  {"estonian":"veli","finnish":"veljet","et":"Mu vend on noorem.","fi":"Veljeni on nuorempi.","cat":"people","cog":0,"d":1},
  {"estonian":"õde","finnish":"sisko","et":"Mu õde on tark.","fi":"Siskoni on viisas.","cat":"people","cog":0,"d":1},
  {"estonian":"laps","finnish":"lapsi","et":"Laps on väike.","fi":"Lapsi on pieni.","cat":"people","cog":0,"d":1},
  {"estonian":"abielus","finnish":"avioliitto","et":"Nad on abielus.","fi":"He ovat avioliitossa.","cat":"people","cog":0,"d":3},
  {"estonian":"koos","finnish":"yhdessä","et":"Nad elavad koos.","fi":"He asuvat yhdessä.","cat":"people","cog":0,"d":1},
  {"estonian":"kohtuma","finnish":"tavata","et":"Ma tahan sind kohtuda.","fi":"Minä tapaan sinut.","cat":"people","cog":0,"d":2},
  {"estonian":"rääkima","finnish":"puhua","et":"Ma räägin eesti keelt.","fi":"Minä puhun suomea.","cat":"people","cog":0,"d":2},
  {"estonian":"kuulma","finnish":"kuulla","et":"Ma kuulen sind.","fi":"Minä kuulen sinut.","cat":"people","cog":0,"d":1},
  {"estonian":"nägema","finnish":"nähdä","et":"Ma näen sind.","fi":"Minä näen sinut.","cat":"people","cog":0,"d":1},
  {"estonian":"ütlema","finnish":"sanoa","et":"Ma ütlen sulle.","fi":"Minä sanon sinulle.","cat":"people","cog":0,"d":2},
  {"estonian":"küsima","finnish":"kysyä","et":"Ma küsin sind.","fi":"Minä kysyn sinulta.","cat":"people","cog":0,"d":2},
  {"estonian":"vastama","finnish":"vastata","et":"Ma vastan sulle.","fi":"Minä vastaan sinulle.","cat":"people","cog":0,"d":2},
  {"estonian":"mõistma","finnish":"ymmärtää","et":"Ma ei mõista.","fi":"Minä en ymmärrä.","cat":"people","cog":0,"d":2},
  {"estonian":"õppima","finnish":"oppia","et":"Ma õpin soome keelt.","fi":"Minä opin suomea.","cat":"people","cog":0,"d":2},
  {"estonian":"õpetama","finnish":"opettaa","et":"Õpetaja õpetab meile.","fi":"Opettaja opettaa meille.","cat":"people","cog":0,"d":2},
  {"estonian":"tegema","finnish":"tehdä","et":"Ma töötän hommikul.","fi":"Minä työskentelen aamulla.","cat":"people","cog":0,"d":2},
  {"estonian":"minema","finnish":"mennä","et":"Ma lähen.","fi":"Minä menen.","cat":"people","cog":0,"d":1},
  {"estonian":"tulema","finnish":"tulla","et":"Tule siia!","fi":"Tule tänne!","cat":"people","cog":0,"d":1},
  {"estonian":"jääma","finnish":"jäädä","et":"Jää siia!","fi":"Jää tänne!","cat":"people","cog":0,"d":1},
  {"estonian":"andma","finnish":"antaa","et":"Anna mulle see.","fi":"Anna minulle tämä.","cat":"people","cog":0,"d":1},
  {"estonian":"võtma","finnish":"ottaa","et":"Võta see!","fi":"Ota tämä!","cat":"people","cog":0,"d":1},
  {"estonian":"panema","finnish":"panna","et":"Pane see lauale.","fi":"Laita tämä pöydälle.","cat":"people","cog":0,"d":1},
  {"estonian":"tuleb","finnish":"tulee","et":"Mul tuleb vettä.","fi":"Minulla on vesi tulossa.","cat":"people","cog":0,"d":2},
  {"estonian":"saama","finnish":"saada","et":"Ma saan uue auto.","fi":"Saan uuden auton.","cat":"people","cog":0,"d":1},
  {"estonian":"töö","finnish":"työ","et":"Töö on raske.","fi":"Työ on raskas.","cat":"work","cog":0,"d":1},
  {"estonian":"töökoht","finnish":"työpaikka","et":"Mul on uus töökoht.","fi":"Minulla on uusi työpaikka.","cat":"work","cog":0,"d":2},
  {"estonian":"palk","finnish":"palkka","et":"Palk on hea.","fi":"Palkka on hyvä.","cat":"work","cog":0,"d":1},
  {"estonian":"puhkus","finnish":"loma","et":"Mul on puhkus.","fi":"Minulla on loma.","cat":"work","cog":0,"d":1},
  {"estonian":"intervjuu","finnish":"haastattelu","et":"Mul on intervjuu homme.","fi":"Minulla on haastattelu huomenna.","cat":"work","cog":0,"d":2},
  {"estonian":"cv","finnish":"ansioluettelo","et":"Saada mu cv.","fi":"Lähettäkää ansioluetteloni.","cat":"work","cog":0,"d":2},
  {"estonian":"oskama","finnish":"osata","et":"Ma oskan rääkida.","fi":"Minä osaan puhua.","cat":"work","cog":0,"d":2},
  {"estonian":"sobima","finnish":"sopia","et":"See ei sobi.","fi":"Tämä ei sovi.","cat":"work","cog":0,"d":1},
  {"estonian":"hoolima","finnish":"huolehtia","et":"Ma hoolin sinust.","fi":"Huoleni sinusta.","cat":"people","cog":0,"d":2},
  {"estonian":"armastama","finnish":"rakastaa","et":"Ma armastan sind.","fi":"Minä rakastan sinua.","cat":"people","cog":0,"d":2},
  {"estonian":"naima","finnish":"naida","et":"Ma naisin täna.","fi":"Menin naimisiin tänään.","cat":"people","cog":0,"d":2},
  {"estonian":"sündima","finnish":"syntyä","et":"Laps sündis täna.","fi":"Lapsi syntyi tänään.","cat":"people","cog":0,"d":2},
]
