"""Seed Part 5: Health & Body (40 words)"""
SEED_PART5 = [
  {"estonian":"arst","finnish":"lääkäri","et":"Ma lähen arsti juurde.","fi":"Menen lääkärin luo.","cat":"health","cog":0,"d":1},
  {"estonian":"haigla","finnish":"sairaala","et":"Haigla on lähedal.","fi":"Sairaala on lähellä.","cat":"health","cog":0,"d":1},
  {"estonian":"apteek","finnish":"apteekki","et":"Apteek on avatud.","fi":"Apteekki on auki.","cat":"health","cog":0,"d":1},
  {"estonian":"ravim","finnish":"lääke","et":"Ma võtan ravimi.","fi":"Otan lääkettä.","cat":"health","cog":0,"d":2},
  {"estonian":"valu","finnish":"kipu","et":"Mul on valu.","fi":"Minulla on kipu.","cat":"health","cog":0,"d":1},
  {"estonian":"kõrvavalu","finnish":"korvakipu","et":"Mul on kõrvavalu.","fi":"Minulla on korvakipu.","cat":"health","cog":0,"d":2},
  {"estonian":"köha","finnish":"yskä","et":"Mul on köha.","fi":"Minulla on yskä.","cat":"health","cog":0,"d":1},
  {"estonian":"kuum","finnish":"kuuma","et":"Ma olen kuum.","fi":"Minulla on kuume.","cat":"health","cog":0,"d":1},
  {"estonian":"haige","finnish":"sairas","et":"Ma olen haige.","fi":"Olen sairas.","cat":"health","cog":0,"d":1},
  {"estonian":"terve","finnish":"terve","et":"Ma olen terve.","fi":"Olen terve.","cat":"health","cog":1,"d":1},
  {"estonian":"tervisekeskus","finnish":"terveyskeskus","et":"Tervisekeskus on avatud.","fi":"Terveyskeskus on auki.","cat":"health","cog":0,"d":3},
  {"estonian":"käsi","finnish":"käsi","et":"Mu käsi on soe.","fi":"Kädeni on lämmin.","cat":"body","cog":1,"d":1},
  {"estonian":"jalg","finnish":"jalka","et":"Mu jalg on väsinud.","fi":"Jalkani on väsynyt.","cat":"body","cog":0,"d":1},
  {"estonian":"pea","finnish":"pää","et":"Mu pea valutab.","fi":"Pääni sattuu.","cat":"body","cog":1,"d":1},
  {"estonian":"silm","finnish":"silmä","et":"Mu silm on sinine.","fi":"Silmäni on sininen.","cat":"body","cog":0,"d":1},
  {"estonian":"kõrv","finnish":"korva","et":"Mu kõrv valutab.","fi":"Korvani sattuu.","cat":"body","cog":0,"d":1},
  {"estonian":"suu","finnish":"suu","et":"Mu suu on kuiv.","fi":"Suuni on kuiva.","cat":"body","cog":1,"d":1},
  {"estonian":"hammas","finnish":"hammas","et":"Mu hammas valutab.","fi":"Hammastani sattuu.","cat":"body","cog":1,"d":1},
  {"estonian":"selg","finnish":"selkä","et":"Mu selg valutab.","fi":"Selkäni sattuu.","cat":"body","cog":0,"d":1},
  {"estonian":"kõht","finnish":"vatsa","et":"Mu kõht valutab.","fi":"Vatsani sattuu.","cat":"body","cog":0,"d":1},
  {"estonian":"süda","finnish":"sydän","et":"Mu süda lööb kiiresti.","fi":"Sydäni lyö nopeasti.","cat":"body","cog":0,"d":2},
  {"estonian":"kops","finnish":"keuhko","et":"Mu kopsud on täis.","fi":"Keuhkoni ovat täynnä.","cat":"body","cog":0,"d":3},
  {"estonian":"luu","finnish":"luu","et":"Mul on luu murdunud.","fi":"Luuni on murtunut.","cat":"body","cog":1,"d":2},
  {"estonian":"lihas","finnish":"lihas","et":"Mu lihased on väsinud.","fi":"Lihaseni ovat väsyneet.","cat":"body","cog":0,"d":2},
  {"estonian":"nägu","finnish":"kasvot","et":"Mu nägu on punane.","fi":"Kasvoni ovat punaiset.","cat":"body","cog":0,"d":1},
  {"estonian":"juuksed","finnish":"hiukset","et":"Mu juuksed on pikad.","fi":"Hiukseni ovat pitkät.","cat":"body","cog":0,"d":1},
  {"estonian":"sõrm","finnish":"sormi","et":"Mu sõrm on haige.","fi":"Sormeni on sairas.","cat":"body","cog":0,"d":2},
  {"estonian":"varvas","finnish":"varvas","et":"Mu varvas on sinine.","fi":"Varpaani on sininen.","cat":"body","cog":1,"d":2},
  {"estonian":"küünarnukk","finnish":"kyynärpää","et":"Mu küünarnukk valutab.","fi":"Kyynärpääni sattuu.","cat":"body","cog":0,"d":3},
  {"estonian":"põlv","finnish":"polvi","et":"Mu põlv valutab.","fi":"Polveni sattuu.","cat":"body","cog":0,"d":1},
  {"estonian":"õlg","finnish":"olka","et":"Mu õlg on kangestunud.","fi":"Olkani on kangistunut.","cat":"body","cog":0,"d":2},
  {"estonian":"nukk","finnish":"niska","et":"Mu nukk on kangestunud.","fi":"Niskani on kangistunut.","cat":"body","cog":0,"d":2},
  {"estonian":"tervisekindlustus","finnish":"sairausvakuutus","et":"Kas sul on tervisekindlustus?","fi":"Onko sinulla sairausvakuutusta?","cat":"health","cog":0,"d":3},
  {"estonian":"vaktsiin","finnish":"rokotus","et":"Kas sa oled vaktsineeritud?","fi":"Oletko rokotettu?","cat":"health","cog":0,"d":3},
  {"estonian":"operatsioon","finnish":"leikkaus","et":"Mul on operatsioon plaanis.","fi":"Minulla on leikkaus suunniteltu.","cat":"health","cog":0,"d":3},
  {"estonian":"röntgen","finnish":"röntgen","et":"Ma lähen röntgeni.","fi":"Menen röntgeniin.","cat":"health","cog":1,"d":2},
  {"estonian":"vererõhk","finnish":"verenpaine","et":"Mul on kõrge vererõhk.","fi":"Minulla on korkea verenpaine.","cat":"health","cog":0,"d":3},
  {"estonian":"allergia","finnish":"allergia","et":"Mul on allergia.","fi":"Minulla on allergia.","cat":"health","cog":1,"d":2},
  {"estonian":"tablett","finnish":"tabletti","et":"Võta tablett enne söömist.","fi":"Ota tabletti ennen syömistä.","cat":"health","cog":0,"d":2},
  {"estonian":"pleister","finnish":"laastari","et":"Kas sul on pleister?","fi":"Onko sinulla laastaria?","cat":"health","cog":0,"d":2},
]
