"""Additional seed words — Part 2: Food & Drink (50 words)"""
SEED_PART2 = [
  {"estonian":"leib","finnish":"leipä","et":"Leib on värske.","fi":"Leipä on tuore.","cat":"food","cog":1,"d":1},
  {"estonian":"piim","finnish":"maito","et":"Piim on külm.","fi":"Maito on kylmä.","cat":"food","cog":0,"d":1},
  {"estonian":"sai","finnish":"sämpylä","et":"Sai on hea.","fi":"Sämpylä on hyvä.","cat":"food","cog":0,"d":1},
  {"estonian":"õlu","finnish":"olut","et":"Õlu on külm.","fi":"Olut on kylmä.","cat":"food","cog":1,"d":1},
  {"estonian":"kohv","finnish":"kahvi","et":"Kohv on tugev.","fi":"Kahvi on vahva.","cat":"food","cog":1,"d":1},
  {"estonian":"tee","finnish":"tee","et":"Tee on soe.","fi":"Tee on kuuma.","cat":"food","cog":1,"d":1},
  {"estonian":"suhkur","finnish":"sokeri","et":"Suhkur on magus.","fi":"Sokeri on makea.","cat":"food","cog":0,"d":2},
  {"estonian":"sool","finnish":"suola","et":"Sool on soolane.","fi":"Suola on suolainen.","cat":"food","cog":1,"d":1},
  {"estonian":"liha","finnish":"liha","et":"Liha on maitsev.","fi":"Liha on makoinen.","cat":"food","cog":1,"d":1},
  {"estonian":"kala","finnish":"kala","et":"Kala ujub.","fi":"Kala ui.","cat":"food","cog":1,"d":1},
  {"estonian":"kartul","finnish":"peruna","et":"Kartul on küps.","fi":"Peruna on kypsä.","cat":"food","cog":0,"d":2},
  {"estonian":"porgand","finnish":"porkkana","et":"Porgand on hea.","fi":"Porkkana on hyvä.","cat":"food","cog":0,"d":2},
  {"estonian":"sibul","finnish":"sipuli","et":"Sibul tekitab pisaraid.","fi":"Sipuli saattaa kyyneleet.","cat":"food","cog":0,"d":2},
  {"estonian":"kurk","finnish":"kurkku","et":"Kurk on värske.","fi":"Kurkku on tuore.","cat":"food","cog":0,"d":2},
  {"estonian":"tomat","finnish":"tomaatti","et":"Tomat on punane.","fi":"Tomaatti on punainen.","cat":"food","cog":0,"d":2},
  {"estonian":"õun","finnish":"omena","et":"Õun on magus.","fi":"Omena on makea.","cat":"food","cog":0,"d":1},
  {"estonian":"banaan","finnish":"banaani","et":"Banaan on kollane.","fi":"Banaani on keltainen.","cat":"food","cog":0,"d":1},
  {"estonian":"viinamari","finnish":"luumu","et":"Viinamari on magus.","fi":"Luumu on makea.","cat":"food","cog":0,"d":2},
  {"estonian":"maasikas","finnish":"mansikka","et":"Maasikas on punane.","fi":"Mansikka on punainen.","cat":"food","cog":0,"d":2},
  {"estonian":"juust","finnish":"juusto","et":"Juust on kollane.","fi":"Juusto on keltainen.","cat":"food","cog":0,"d":1},
  {"estonian":"muna","finnish":"muna","et":"Muna on värske.","fi":"Muna on tuore.","cat":"food","cog":1,"d":1},
  {"estonian":"supp","finnish":"keitto","et":"Supp on soe.","fi":"Keitto on kuuma.","cat":"food","cog":0,"d":1},
  {"estonian":"salat","finnish":"salaatti","et":"Salat on värske.","fi":"Salaatti on tuore.","cat":"food","cog":0,"d":1},
  {"estonian":"pitsa","finnish":"pizza","et":"Pitsa on hea.","fi":"Pizza on hyvä.","cat":"food","cog":1,"d":1},
  {"estonian":"jää","finnish":"jää","et":"Jääl on hästi külm.","fi":"Jäällä on hyvin kylmä.","cat":"food","cog":1,"d":1},
  {"estonian":"vesi","finnish":"vesi","et":"Vesi on selge.","fi":"Vesi on kirkas.","cat":"food","cog":1,"d":1},
  {"estonian":"maitse","finnish":"maista","et":"Maitse seda!","fi":"Maista tätä!","cat":"food","cog":0,"d":2},
  {"estonian":"söön","finnish":"syön","et":"Ma söön hommikust.","fi":"Minä syön aamupalaa.","cat":"food","cog":0,"d":2},
  {"estonian":"joon","finnish":"juon","et":"Ma joon kohvi.","fi":"Minä juon kahvia.","cat":"food","cog":0,"d":2},
  {"estonian":"näljane","finnish":"nälkäinen","et":"Ma olen näljane.","fi":"Minä olen nälkäinen.","cat":"food","cog":0,"d":2},
  {"estonian":"janune","finnish":"janoinen","et":"Ma olen janune.","fi":"Minä olen janoinen.","cat":"food","cog":0,"d":2},
  {"estonian":"küps","finnish":"kypsä","et":"Liha on küps.","fi":"Liha on kypsä.","cat":"food","cog":0,"d":2},
  {"estonian":"magu","finnish":"maku","et":"Mis magu see on?","fi":"Mikä maku tässä on?","cat":"food","cog":0,"d":2},
  {"estonian":"hapu","finnish":"hapan","et":"See on hapu.","fi":"Tämä on hapan.","cat":"food","cog":0,"d":2},
  {"estonian":"soe","finnish":"lämmin","et":"Supp on soe.","fi":"Keitto on lämmin.","cat":"food","cog":0,"d":1},
  {"estonian":"külm","finnish":"kylmä","et":"Jäätis on külm.","fi":"Jäätelö on kylmä.","cat":"food","cog":0,"d":1},
  {"estonian":"magus","finnish":"makea","et":"Kook on magus.","fi":"Kakku on makea.","cat":"food","cog":0,"d":1},
  {"estonian":"soolane","finnish":"suolainen","et":"Supp on soolane.","fi":"Keitto on suolainen.","cat":"food","cog":0,"d":2},
  {"estonian":"tervislik","finnish":"terveellinen","et":"Kasikõrvits on tervislik.","fi":"Kurkku on terveellinen.","cat":"food","cog":0,"d":3},
  {"estonian":"hommikusöök","finnish":"aamupala","et":"Hommikusöök on tähtis.","fi":"Aamupala on tärkeä.","cat":"food","cog":0,"d":2},
  {"estonian":"lõunasöök","finnish":"lounas","et":"Lõunasöök on valmis.","fi":"Lounas on valmis.","cat":"food","cog":0,"d":2},
  {"estonian":"õhtusöök","finnish":"illallinen","et":"Õhtusöök on kuus.","fi":"Illallinen on kuusi.","cat":"food","cog":0,"d":2},
  {"estonian":"nuga","finnish":"nuudeli","et":"Nuga on hea.","fi":"Nuudeli on hyvä.","cat":"food","cog":0,"d":1},
  {"estonian":"riis","finnish":"riisi","et":"Riis on valge.","fi":"Riisi on valkoinen.","cat":"food","cog":1,"d":1},
  {"estonian":"kana","finnish":"kana","et":"Kana on küps.","fi":"Kana on kypsä.","cat":"food","cog":1,"d":1},
  {"estonian":"veiseliha","finnish":"naudanliha","et":"Veiseliha on kallim.","fi":"Naudanliha on kalliimpi.","cat":"food","cog":0,"d":3},
  {"estonian":"sealiha","finnish":"sianliha","et":"Sealiha on odavam.","fi":"Sianliha on halvempi.","cat":"food","cog":0,"d":3},
  {"estonian":"kook","finnish":"kakku","et":"Kook on magus.","fi":"Kakku on makea.","cat":"food","cog":0,"d":1},
  {"estonian":"jäätis","finnish":"jäätelö","et":"Jäätis on külm.","fi":"Jäätelö on kylmä.","cat":"food","cog":0,"d":1},
  {"estonian":"šokolaad","finnish":"suklaa","et":"Šokolaad on magus.","fi":"Suklaa on makea.","cat":"food","cog":0,"d":1},
]
