"""Seed Part 10: More words to reach 500+ total."""
SEED_PART10 = [
  # Verbs - common actions
  {"estonian":"minema","finnish":"mennä","et":"Ma lähen koju.","fi":"Menen kotiin.","cat":"verbs","cog":0,"d":1},
  {"estonian":"tulema","finnish":"tulla","et":"Tule siia!","fi":"Tule tänne!","cat":"verbs","cog":0,"d":1},
  {"estonian":"sööma","finnish":"syödä","et":"Ma söön õuna.","fi":"Syön omenaa.","cat":"verbs","cog":0,"d":1},
  {"estonian":"jooma","finnish":"juoda","et":"Ma joon vett.","fi":"Juon vettä.","cat":"verbs","cog":0,"d":1},
  {"estonian":"magama","finnish":"nukkua","et":"Ma magan hästi.","fi":"Nukun hyvin.","cat":"verbs","cog":0,"d":1},
  {"estonian":"töötama","finnish":"työskennellä","et":"Ma töötän kontoris.","fi":"Työskentelen toimistossa.","cat":"verbs","cog":0,"d":2},
  {"estonian":"õppima","finnish":"oppia","et":"Ma õpin soome keelt.","fi":"Opin suomea.","cat":"verbs","cog":0,"d":1},
  {"estonian":"mängima","finnish":"pelata","et":"Lapsed mängivad.","fi":"Lapset leikkivät.","cat":"verbs","cog":0,"d":1},
  {"estonian":"lugema","finnish":"lukea","et":"Ma loen raamatut.","fi":"Luen kirjaa.","cat":"verbs","cog":0,"d":1},
  {"estonian":"kirjutama","finnish":"kirjoittaa","et":"Ma kirjutan kirja.","fi":"Kirjoitan kirjeen.","cat":"verbs","cog":0,"d":2},
  {"estonian":"ütlema","finnish":"sanoa","et":"Ma ütlen tere.","fi":"Sanon hei.","cat":"verbs","cog":0,"d":1},
  {"estonian":"küsima","finnish":"kysyä","et":"Ma küsin teed.","fi":"Kysyn tietä.","cat":"verbs","cog":0,"d":1},
  {"estonian":"vastama","finnish":"vastata","et":"Ma vastan küsimusele.","fi":"Vastaan kysymykseen.","cat":"verbs","cog":0,"d":2},
  {"estonian":"ostma","finnish":"ostaa","et":"Ma ostin uue auto.","fi":"Ostin uuden auton.","cat":"verbs","cog":0,"d":1},
  {"estonian":"müüma","finnish":"myydä","et":"Nad müüvad head toitu.","fi":"He myyvät hyvää ruokaa.","cat":"verbs","cog":0,"d":1},
  {"estonian":"nägema","finnish":"nähdä","et":"Ma näen sind.","fi":"Näen sinut.","cat":"verbs","cog":0,"d":1},
  {"estonian":"kuulma","finnish":"kuulla","et":"Ma kuulen muusikat.","fi":"Kuulen musiikkia.","cat":"verbs","cog":0,"d":1},
  {"estonian":"tundma","finnish":"tuntea","et":"Ma tunnen end hästi.","fi":"Tunnen itseni hyväksi.","cat":"verbs","cog":0,"d":2},
  {"estonian":"mõtlema","finnish":"ajatella","et":"Ma mõtlen sinust.","fi":"Ajattelen sinua.","cat":"verbs","cog":0,"d":1},
  {"estonian":"teadma","finnish":"tietää","et":"Ma tean vastust.","fi":"Tiedän vastauksen.","cat":"verbs","cog":0,"d":1},

  # Adjectives
  {"estonian":"suur","finnish":"suuri","et":"Maja on suur.","fi":"Talo on suuri.","cat":"adjectives","cog":1,"d":1},
  {"estonian":"väike","finnish":"pieni","et":"Laps on väike.","fi":"Lapsi on pieni.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"ilus","finnish":"kaunis","et":"Ilm on ilus.","fi":"Sää on kaunis.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"vana","finnish":"vanha","et":"Maja on vana.","fi":"Talo on vanha.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"uus","finnish":"uusi","et":"Auto on uus.","fi":"Auto on uusi.","cat":"adjectives","cog":1,"d":1},
  {"estonian":"hea","finnish":"hyvä","et":"Toit on hea.","fi":"Ruoka on hyvä.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"halb","finnish":"huono","et":"Ilm on halb.","fi":"Sää on huono.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"pikk","finnish":"pitkä","et":"Tee on pikk.","fi":"Tie on pitkä.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"lühike","finnish":"lyhyt","et":"Lugu on lühike.","fi":"Tarina on lyhyt.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"kiire","finnish":"nopea","et":"Rong on kiire.","fi":"Juna on nopea.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"aeglane","finnish":"hidas","et":"Reis on aeglane.","fi":"Matka on hidas.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"raske","finnish":"raskas","et":"Kott on raske.","fi":"Laukku on raskas.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"kerge","finnish":"kevyt","et":"Lumi on kerge.","fi":"Lumi on kevyt.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"tugev","finnish":"vahva","et":"Tuul on tugev.","fi":"Tuuli on vahva.","cat":"adjectives","cog":0,"d":1},
  {"estonian":"nõrk","finnish":"heikko","et":"Signaal on nõrk.","fi":"Signaali on heikko.","cat":"adjectives","cog":0,"d":1},

  # Prepositions & conjunctions
  {"estonian":"ja","finnish":"ja","et":"Mina ja sina.","fi":"Minä ja sinä.","cat":"conjunctions","cog":1,"d":1},
  {"estonian":"või","finnish":"tai","et":"Kas või kohv?","fi":"Kahvi vai tee?","cat":"conjunctions","cog":0,"d":1},
  {"estonian":"aga","finnish":"mutta","et":"Ma tahan, aga ma ei saa.","fi":"Haluan, mutta en saa.","cat":"conjunctions","cog":0,"d":1},
  {"estonian":"sest","finnish":"koska","et":"Ma ei tule, sest ma olen haige.","fi":"En tule, koska olen sairas.","cat":"conjunctions","cog":0,"d":2},
  {"estonian":"kui","finnish":"kun","et":"Kui ma tulen, ma helistan.","fi":"Kun tulen, soitan.","cat":"conjunctions","cog":0,"d":1},
  {"estonian":"enne","finnish":"ennen","et":"Enne söömist.","fi":"Ennen syömistä.","cat":"prepositions","cog":0,"d":1},
  {"estonian":"pärast","finnish":"jälkeen","et":"Pärast tööd.","fi":"Työn jälkeen.","cat":"prepositions","cog":0,"d":1},
  {"estonian":"ilma","finnish":"ilman","et":"Ilma sind.","fi":"Ilman sinua.","cat":"prepositions","cog":0,"d":1},
  {"estonian":"läbi","finnish":"läpi","et":"Läbi metsa.","fi":"Läpi metsän.","cat":"prepositions","cog":0,"d":1},
  {"estonian":"peale","finnish":"jälkeen","et":"Peale tööd lähen koju.","fi":"Työn jälkeen menen kotiin.","cat":"prepositions","cog":0,"d":2},

  # Question words & pronouns
  {"estonian":"mina","finnish":"minä","et":"Ma olen õpilane.","fi":"Minä olen opiskelija.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"sina","finnish":"sinä","et":"Sa oled sõber.","fi":"Sinä olet ystävä.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"tema","finnish":"hän","et":"Ta on õpetaja.","fi":"Hän on opettaja.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"meie","finnish":"me","et":"Me oleme õpilased.","fi":"Me olemme opiskelijat.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"teie","finnish":"te","et":"Te olete õpetajad.","fi":"Te olette opettajat.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"nemad","finnish":"he","et":"Nad on sõbrad.","fi":"He ovat ystäviä.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"see","finnish":"tämä","et":"See on mu raamat.","fi":"Tämä on kirjani.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"too","finnish":"tuo","et":"Too on suur.","fi":"Tuo on suuri.","cat":"pronouns","cog":0,"d":1},
  {"estonian":"kes","finnish":"kuka","et":"Kes sa oled?","fi":"Kuka sinä olet?","cat":"questions","cog":0,"d":1},
  {"estonian":"mida","finnish":"mitä","et":"Mida sa teed?","fi":"Mitä sinä teet?","cat":"questions","cog":0,"d":1},

  # Negation
  {"estonian":"ei","finnish":"ei","et":"Ei, aitäh.","fi":"Ei, kiitos.","cat":"negation","cog":1,"d":1},
  {"estonian":"mitte","finnish":"ei","et":"Mitte nii.","fi":"Ei niin.","cat":"negation","cog":0,"d":1},
  {"estonian":"mitte kunagi","finnish":"ei koskaan","et":"Mitte kunagi!","fi":"Ei koskaan!","cat":"negation","cog":0,"d":2},
  {"estonian":"mitte keegi","finnish":"ei kukaan","et":"Mitte keegi ei tea.","fi":"Ei kukaan tiedä.","cat":"negation","cog":0,"d":2},
  {"estonian":"mitte midagi","finnish":"ei mitään","et":"Ma ei tea midagi.","fi":"En tiedä mitään.","cat":"negation","cog":0,"d":2},
]
